### ISSUE TITLE
App Buttons permanently disabeled (grey)

### ISSUE THREAD

**Issue by Sogolumbo** [OxfordHCC/tracker-control-android#102]
The buttons in the app list are permanently disabled. They don't get enabeled by restarting or reenabeling the app.
![IMG_20200824_150705](https://user-images.githubusercontent.com/33571916/91049044-de396e80-e61c-11ea-8f4a-a49e875b53fe.png)

**Comment by kasnder** [comment]
Wow. That's very weird. Thanks for reptoting. Does this re-occur if you delete all app data? You might want to make a backup first.

**Comment by Sogolumbo** [comment]
Deleting all app data does fix the disabled buttons.
Unfortunatly my export file was empty (0 bytes). Restoring the empty file takes the app back into the broken state.

After deleting the app data I was not sure whether everything was really working so I just reinstalled the app.

**Comment by kasnder** [comment]
I'm sorry for all the trouble, but hope the app will be working fine for you now.

Let me know if this issue, or other issues, pop up!

**Comment by kasnder** [comment]
Closing this for now.
