### ISSUE TITLE
Fixed: Can't install on Android 11

### ISSUE THREAD

**Issue by pivic** [OxfordHCC/tracker-control-android#105]
I know, I'm running a beta version of the coming Android 11.

Still, it's impossible to install the app via F-Droid.

The error message is: 'Error installing TrackerControl.

Failed to install due to an unknown error.'

Please let me know if I can help further in any way.

**Comment by kasnder** [comment]
Weird, thanks for reporting! I don't have a testing device yet.

If have have access to the ADB, you could try to install from the command line: 'adb install [path to APK'

**Comment by kasnder** [comment]
This should give a more elaborate error message.

**Comment by pivic** [comment]
Thanks, but unfortunately I don't have access to ADB...

**Comment by kasnder** [comment]
If you have a free minute, this article describes how to set it up.

No need to install anything. Just download official Android tools.

https://www.xda-developers.com/quickly-install-adb/

**Comment by duggalsu** [comment]
Confirmed that it cannot be installed on final release of Android 11. Here is the adb install log -

adb: failed to install ../net.kollnig.missioncontrol.fdroid_2020082701.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package net.kollnig.missioncontrol.fdroid]

This may be helpful - https://stackoverflow.com/questions/2914105/what-is-install-parse-failed-no-certificates-error

**Comment by kasnder** [comment]
Thanks for clarifying this. It seems to be a problem with F-Droid:

https://gitlab.com/fdroid/fdroidserver/-/issues/827

**Comment by kasnder** [comment]
I guess the GitHub version should work:

https://github.com/OxfordHCC/tracker-control-android/releases

**Comment by pivic** [comment]
> I guess the GitHub version should work:
> 
> https://github.com/OxfordHCC/tracker-control-android/releases

I have upgraded to the final version of Android 11 and can confirm that the GitHub version works brilliantly to download and install. Thanks a lot, @kasnder

**Comment by duggalsu** [comment]
Thanks!

**Comment by kasnder** [comment]
Glad to hear that and thanks for flagging!

**Comment by kasnder** [comment]
Have now downgraded the target version to Android 10. This should do the trick until F-Droid fixes this issue.

**Comment by kasnder** [comment]
This should go online soon on F-Droid. Alternatively, you can download the anniversary release directly from GitHub:

https://github.com/OxfordHCC/tracker-control-android/releases/tag/2020090901

**Comment by kasnder** [comment]
Related commit: https://github.com/OxfordHCC/tracker-control-android/commit/b6fef941d6d2ade47376a80e6185e7a35a429e9f

**Comment by frangon** [comment]
Hi,

I tried to install the anniversary version directly from github and I'm not able to. I only get the message "App not installed."
I have Android 11 on Pixel 2XL device 

Thanks
![Screenshot_20200910-230556](https://user-images.githubusercontent.com/71099965/92797555-d9b1db80-f3ba-11ea-9b12-3b699c30b125.png)

**Comment by kasnder** [comment]
Oh wow. This is very strange. I'm running a Pixel 4 with Android 11 and no problem. Let me double check.

**Comment by kasnder** [comment]
@frangon The problem might occur from having the F-Droid version still installed. These are signed with another signature and not compatible. If you backup your settings, uninstall any previous version, you should be able to install.

At least, this is what works for me.

**Comment by kasnder** [comment]
The might be an issue with the F-Droid version being still installed, but you can't see it. This might cause an issue.

Try the latest version. I made a change that addresses this problem.

**Comment by frangon** [comment]
Thanks kasnder. That fixed the problem.
I successfully installed the new version.
