### ISSUE TITLE
Turn off button to block internet was more intuitive than it being only one where on = allow.

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#114]
While I understand the thought process behind "on = allow internet" it being the ONLY button where having it enabled is less restrictive is couterintuitive.  Having the option be "Block internet" and then have it OFF to allow and on to block would fit the pattern of the other buttons.

**Comment by kasnder** [comment]
I absolutely agree that Internet is less restrictive and that is not perfect. Two reasons why this behaviour may not be too bad:

1. Monitoring is also 'allowed' when the switch is on.
2. You can easily scan over the buttons and see which ones are changed from the default: those ones that are disabled.
