### ISSUE TITLE
Problem with "da fit" app with latest (09/11) github version tracker control

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#117]
Ran into a problem with the "da fit" smartwatch app.  It only showed one connection attempt to yahoo.com which was identified as "essential" however inside the app when you entered any zip code or city name in the weather section no results came up.  I finally had to disable monitoring of the app entirely and suddenly the weather section worked just fine.  "da fit" is used by many of the $30 chinese smartwatch's.  The one I was testing is the umidigi uwatch 2s.  Should be easily repeatable and the app is free to use.  No hardware should be required.

**Comment by kasnder** [comment]
When I disable the 'essential' section, it works for me. The service seems to be using the Yahoo Weather service.

**Comment by famewolf** [comment]
I'm pretty sure at one point I tried that but perhaps I didn't close the app fully and restart it.  For some reason I was thinking "essential" was disabled by default.  Thanks for checking.
