### ISSUE TITLE
Make 'unblocked' text bold

### ISSUE THREAD

**Issue by kasnder** [OxfordHCC/tracker-control-android#118]
This would give users more feedback.

**Comment by siebenbrodt** [comment]
Suggestion to improve readability: make the company names in bold to help distinguish it from domain names, and highlight 'unblocked' with color so it will stand out well among the gray lines.
![trackercontrol-mockup](https://user-images.githubusercontent.com/38620063/116996373-f9986580-ace3-11eb-867f-ab4bedbc5b6a.png)

**Comment by kasnder** [comment]
I like this! I've added this now: https://github.com/OxfordHCC/tracker-control-android/commit/0d10c8380e5c70e3293dbf8990e8592087e7c427
