### ISSUE TITLE
Don't block, just track

### ISSUE THREAD

**Issue by jakob1379** [OxfordHCC/tracker-control-android#123]
I can't figure find the function to don't block anything or in particular, won't block essentials for all apps, only on a per app basis. I love the concept of the app but I don't want it to block anything just yet, so please make this a feature in the settings.

**Comment by kasnder** [comment]
Great suggestion! In the meantime, I recommend to get the version from the Play Store. This comes without blocking.

**Comment by jakob1379** [comment]
I'll check it out.

**Comment by kasnder** [comment]
As a bonus, if you don’t block, you’ll find more trackers. Very interesting to see.

**Comment by jakob1379** [comment]
> As a bonus, if you don’t block, you’ll find more trackers. Very interesting to see.

Quite an interesting sideeffect, indeed.

**Comment by kasnder** [comment]
The upcoming release will add a setting to disable blocking, but keep detecting trackers.
