### ISSUE TITLE
Tracker-blocking can't be enabled. SecurityException: INTERACT_ACROSS_USERS

### ISSUE THREAD

**Issue by TechD123** [OxfordHCC/tracker-control-android#124]
Downloaded TrackerControl directly from Github (2020.09.10). Everytime I try to start Tracker Control, I get this error: Unexpected Error: 'java-lang-SecurityException: getpackageUid: Neither user x nor current process has android.permission.INTERACT_ACROSS_USERS'

**Comment by kasnder** [comment]
Thanks for reporting, and sorry you’re having trouble.

This seems to be related to this issue: https://github.com/AdguardTeam/AdguardForAndroid/issues/173

**Comment by kasnder** [comment]
Do you have multiple users on your device, or use a work profile?

**Comment by TechD123** [comment]
I stumbled upon that same thread too, haha. I do have two user profiles on my Android tablet. However, I used the main/admin user profile to install TrackerControl. According to [this](https://forum.xda-developers.com/showpost.php?p=69895217&postcount=1920), apps from the Play Store don't have this issue. How does the Play Store version differ? Does it block the same amount of trackers?

**Comment by kasnder** [comment]
The PlayStore version doesn’t have blocking. It’s just an analysis tool. I’ll try to investigate this more, but have failed to do so in the past. So, not sure how much I can do for you. I’m super sorry .

**Comment by TechD123** [comment]
Ok, thanks for trying to help! To be clear though, this _should_ only happen on devices with mutiple user profiles?

**Comment by kasnder** [comment]
Yep, I think this is the issue!
