### ISSUE TITLE
allow all essential and uncategorized toggles

### ISSUE THREAD

**Issue by DevJackSmith** [OxfordHCC/tracker-control-android#126]
Hello, thanks for great app. As a user i want to be able to set all 200+ apps on my phone to allow Essential and Uncategorized with one click each (two clicks total). Please consider this feature request.

**Comment by kasnder** [comment]
Thanks for this suggestion! There's a non-strict mode in the settings that excludes essehtzak trackers by default. Haven't considered uncategorised trackers, but will look into it!

Do uncategorised trackers break many apps for you? Why do you want to disable it?

**Comment by DevJackSmith** [comment]
Thank you. Just used the non strict mode and it worked perfectly. I'm not sure about many apps breaking because of uncategorized, but a few did yes. I would think it's useful for different users to be able to disable/enable any category throughout the whole tc app.

**Comment by kasnder** [comment]
I think the goal is to categorise the uncategorised trackers at some point.

These also contain the adblocking hosts.

So, I'll close this issue for now.
