### ISSUE TITLE
Global domain whitelist

### ISSUE THREAD

**Issue by b3wii** [OxfordHCC/tracker-control-android#135]
Thanx for making this great app! I would love to see a global whitelist for domains/ip.

**Comment by kasnder** [comment]
Thanks for this suggestion. Do you have any particular domains that cause problems for you?

**Comment by b3wii** [comment]
> Thanks for this suggestion. Do you have any particular domains that cause problems for you?

How can I find out if theres no posibility to whitelist?

**Comment by kasnder** [comment]
> > Thanks for this suggestion. Do you have any particular domains that cause problems for you?
> 
> How can I find out if theres no possibility to whitelist?

There’s currently no global whitelist feature, unfortunately. There’s only whitelisting certain companies per app. Yet, you can click on the company names (instead of the switch buttons), and thereby finely manage blocking.

**Comment by iiitomo** [comment]
> you can click on the company names (instead of the switch buttons), and thereby finely manage blocking.

b3wii : can the ticket be closed?

**Comment by kasnder** [comment]
I’ll implementing a different solution soon. A setting to enable domain-based blocking. So, I’ll close this.
