### ISSUE TITLE
User information

### ISSUE THREAD

**Issue by ameetkoomar** [OxfordHCC/tracker-control-android#138]
I'm not a tech person and my apologies if concern sound silly:

I don't know if I've to block the advertising, analytics etc or app does automatic.

if I've to block should I slide the bar toward left. because it doesnt say block or unblock (not clear for a normal person like me)

**Comment by kasnder** [comment]
Good question. All blocked automatically. You'll notice that things might break if blocking is enabled.

Any idea how to make this clearer? I'm really trying hard to make the app as straightforward as possible, and would love to hear your ideas!

**Comment by ameetkoomar** [comment]
Thank you for your quick response

My suggestion would be give some notification which say block or unblock when we slide the bar.

overall app is 5 star
OSM work keep it up

**Comment by kasnder** [comment]
This is a great suggestion!!

**Comment by kasnder** [comment]
This is now implemented.
