### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by bege10** [OxfordHCC/tracker-control-android#14]
On my Samsung Galaxy S5 Plus (SM-G901F), LineageOS for microG 16 (Android 9) I have ~500MB free RAM. TrackerControl uses 200 of it. This is much more than any other app uses and far too much to work smoothly with the phone. Is there a chance to significantly reduce the RAM usage? Or any other solution for phones with limited RAM?

**Comment by kasnder** [comment]
Thanks for reporting this. You’re currently using the prototype of the app, which is far from perfect. I’m sorry. I’m planning a complete rewrite of the app, which should solve this problem. It’s a challenging endeavour though, which will take some time.

**Comment by bege10** [comment]
The app looks quite perfect already. So thank you for your work and your plan to perfect the app.

**Comment by kasnder** [comment]
I’m now working on the new release, which seems to have a RAM consumption 60-80MB. Trying to have it ready before the New Year.. :) Thanks for raising my attention to this!

**Comment by kasnder** [comment]
New release is online now. This should fix your issue.

**Comment by bege10** [comment]
Thank you for your work. The new version has 100MB RAM consumption on my phone which is still a bit much for 500MB free RAM.

**Comment by kasnder** [comment]
I’m sorry to hear that and thanks for your continued support. Do you have any experience with the RAM consumption of other ad-blocking apps, such as Blockada or NetGuard? It’d be interesting to compare their RAM consumption. Also, is your phone rooted?

**Comment by bege10** [comment]
I noticed that the new version completely blocked traffic. I could solve it by deleting app data. The RAM usage is between 40 and 100MB since, mostly at the lower end. So I think this is OK.
I temporarily installed NetGuard, it needs ~150MB
Yes, my phone is rooted.

**Comment by kasnder** [comment]
Thanks for the feedback! Rooted phones might allow for blocking of tracking without the need for VPN, reducing RAM usage. However, at the current stage, the objective is to make it accessible for as many users as possible. If the situation should change, I'll let you know!

**Comment by bege10** [comment]
I don't quite understand. Currently TC uses VPN and traffic is attributed both to other apps and TC:

![Screenshot_20200111-121926_GlassWire](https://user-images.githubusercontent.com/1184237/72352676-fdfdd100-36e2-11ea-809f-6ce49e53dcab.png)

**Comment by kasnder** [comment]
This probably happens, when you exclude certain apps from blocking in TC. They then bypass the VPN.

**Comment by kasnder** [comment]
RAM usage seems to be related to having opened the UI at some point, as you mentioned in issue #22. In my understanding, Android just keeps the UI in the RAM, to re-open it at a later stage. If you should run short of RAM, Android would free up this memory automatically.

**Comment by bege10** [comment]
> 
> 
> This probably happens, when you exclude certain apps from blocking in TC. They then bypass the VPN.

These apps are not excluded.
