### ISSUE TITLE
Whitelist for VPN

### ISSUE THREAD

**Issue by FreggelBuster** [OxfordHCC/tracker-control-android#148]
Hi,
it would be great if there were a thing like a Whitelist for Apps
to be left untouched. 

I have Problems with my Banking and Email App, they didn't receive 
push mails, so I didn't get the notification to verify the account access.

Tschau Freggel_Buster

**Comment by kasnder** [comment]
Sorry to hear this. Have you enabled 'show system apps' from the advanced settings? This can break things, if Google Play Services is blocked.

**Comment by FreggelBuster** [comment]
Thanks for the hint. 
Yupp, I played with this on my tablet, but the the Push Mail problem is also on my phone .

All devices are running on Oreo.

Tschau Freggel_Buster

**Comment by kasnder** [comment]
I see. It might also be the case the your email provider is amongst those domains blocked. Google Mail is a widespread issue. Does the app work if you disable blocking for all tracker categories?

**Comment by kasnder** [comment]
I’ve thought about this again. I think you should be able to replicate this behaviour by disabling “Monitoring” for the apps that fail for you. This excludes these apps from going through the VPN of TC.
