### ISSUE TITLE
Not working with nebulo like net-guard

### ISSUE THREAD

**Issue by ZOASR** [OxfordHCC/tracker-control-android#154]
Vpn DNS is not working using port forwarding using Nebulo
But it works fine with Net-Guard, I'd assume it would in both TC and NG since TC is a fork of Net-Guard.

**Comment by kasnder** [comment]
Weird. It works for me. Did you disable 'Monitoring' for Nebulo?

**Comment by ZOASR** [comment]
> Weird. It works for me. Did you disable 'Monitoring' for Nebulo?

Yes, i have monitoring disabled in TC.

**Comment by ZOASR** [comment]
> Weird. It works for me. Did you disable 'Monitoring' for Nebulo?

I've discovered what i'm doing wrong, Nebulo doesn't query dns requests on apps that have **Monitoring** disabled on them, since technically these apps are not relayed through TC.

Sorry for the inconvenience.
