### ISSUE TITLE
Google Ads in spite of TC

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#155]
I'm not sure what it is with this new app that XDA developer just came out with but it has some pretty annoying ads and they continue to show up even though no advertising is identified by tracker control. Google ads are shown under fingerprinting but are listed as blocked yet the ads are still showing.

![Screenshot_20210125-142551](https://user-images.githubusercontent.com/4558832/105755506-5e8c3480-5f19-11eb-8c41-5e74bf491ccb.jpg)
![Screenshot_20210124-185327](https://user-images.githubusercontent.com/4558832/105755535-6a77f680-5f19-11eb-8590-2a547b3fee9c.jpg)
![Screenshot_20210125-142610](https://user-images.githubusercontent.com/4558832/105755552-71066e00-5f19-11eb-9aa7-2996af3e362f.jpg)

**Comment by kasnder** [comment]
Thanks for reporting. I’ll investigate this!

**Comment by kasnder** [comment]
It’s also been reported that this app might not be caught by TC: https://play.google.com/store/apps/details?id=com.arjanvlek.oxygenupdater

**Comment by famewolf** [comment]
> It’s also been reported that this app might not be caught by TC: https://play.google.com/store/apps/details?id=com.arjanvlek.oxygenupdater

Yeah ironically I can confirm that one as well......
![Screenshot_20210126-153126](https://user-images.githubusercontent.com/4558832/105901962-01ad7e80-5fec-11eb-8881-dff12da44695.jpg)
![Screenshot_20210126-153207](https://user-images.githubusercontent.com/4558832/105901976-07a35f80-5fec-11eb-972a-2e4e2a5a467c.jpg)
![Screenshot_20210126-153212](https://user-images.githubusercontent.com/4558832/105901993-0b36e680-5fec-11eb-98ba-dfc8ef8e785f.jpg)

**Comment by kasnder** [comment]
The problem might lie in the Google Play Services. These can share data with Google, possibly also ads.. Are you running a replacement of Google Play Services by any change?

**Comment by famewolf** [comment]
No...I use several google products so not really an option.   You can add the xda-developer app to this list.

So I might need to install adaway on top of tracker control?  Can you use their blocklist?

**Comment by kasnder** [comment]
You can configure additional blocklists from the settings.

**Comment by famewolf** [comment]
True but that's a manual process for append rather than a "download and append" process like the main host.   The adaway list gets updated fairly frequently.

**Comment by kasnder** [comment]
You can choose a different blocklist if you want from the settings, by settings a URL.

**Comment by kasnder** [comment]
I don't think there's much I can do to fix this. Unfortunately, Google services are integrated deeply into many Android systems.

**Comment by kasnder** [comment]
I've actually changed my mind. There might be a way to do this better, and I'll investigate this.

See #163
