### ISSUE TITLE
Wireshark is listing trackers that the app is showing were blocked

### ISSUE THREAD

**Issue by IL2P** [OxfordHCC/tracker-control-android#157]
Wireshark is listing trackers that the app is showing were blocked. Does that mean these requests are bypassing tracker control?

Phone connected to Laptop Wifi Hotspot (Connectify)

Wireshark monitoring the Hotspot device.

Tracker Control showing trackers for app "Force Stop Apps" as blocked.

Tracker Control Log shows all of these as successfully blocked: *umeng.com, *doubleclick.net, *googleapis.com, *googlesyndication.com

Wireshark is seeing all of these listings that the app shows as blocked.

Wireshark output: 

No.     Time           Source                Destination           Protocol Length Info
   4055 5828.281084    LAPTOP-JPYKT433.local 192.168.137.77        UDP      209    clearvisn(2052) → 40706 Len=167

Frame 4055: 209 bytes on wire (1672 bits), 209 bytes captured (1672 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: LAPTOP-JPYKT433.local (0e:54:15:75:2c:77), Dst: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2)
Internet Protocol Version 4, Src: LAPTOP-JPYKT433.local (192.168.137.1), Dst: 192.168.137.77 (192.168.137.77)
User Datagram Protocol, Src Port: clearvisn (2052), Dst Port: 40706 (40706)
Data (167 bytes)

0000  04 6d 81 80 00 01 00 03 00 01 00 00 05 75 6c 6f   .m...........ulo
0010  67 73 05 75 6d 65 6e 67 03 63 6f 6d 00 00 1c 00   gs.umeng.com....
0020  01 c0 0c 00 05 00 01 00 00 01 2c 00 21 05 75 6c   ..........,.!.ul
0030  6f 67 73 05 75 6d 65 6e 67 03 63 6f 6d 03 67 64   ogs.umeng.com.gd
0040  73 0a 61 6c 69 62 61 62 61 64 6e 73 c0 18 c0 2d   s.alibabadns...-
0050  00 05 00 01 00 00 00 bf 00 09 06 61 6c 6f 67 75   ...........alogu
0060  73 c0 12 c0 5a 00 05 00 01 00 00 00 3c 00 09 06   s...Z.......<...
0070  61 6c 6f 67 75 73 c0 33 c0 3d 00 06 00 01 00 00   alogus.3.=......
0080  00 62 00 23 06 67 64 73 6e 73 31 c0 41 04 6e 6f   .b.#.gdsns1.A.no
0090  6e 65 00 78 4a 19 21 00 00 07 08 00 00 02 58 00   ne.xJ.!.......X.
00a0  00 0e 10 00 00 01 68                              ......h

No.     Time           Source                Destination           Protocol Length Info
   4056 5828.283151    LAPTOP-JPYKT433.local 192.168.137.77        UDP      490    clearvisn(2052) → 35979 Len=448

Frame 4056: 490 bytes on wire (3920 bits), 490 bytes captured (3920 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: LAPTOP-JPYKT433.local (0e:54:15:75:2c:77), Dst: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2)
Internet Protocol Version 4, Src: LAPTOP-JPYKT433.local (192.168.137.1), Dst: 192.168.137.77 (192.168.137.77)
User Datagram Protocol, Src Port: clearvisn (2052), Dst Port: 35979 (35979)
Data (448 bytes)

0000  f4 ef 81 80 00 01 00 0c 00 00 00 00 07 70 6c 62   .............plb
0010  73 6c 6f 67 05 75 6d 65 6e 67 03 63 6f 6d 00 00   slog.umeng.com..
0020  1c 00 01 c0 0c 00 05 00 01 00 00 00 3c 00 2d 13   ............<.-.
0030  64 75 61 6c 73 74 61 63 6b 2d 6e 61 36 31 2d 6e   dualstack-na61-n
0040  61 36 32 09 77 61 67 62 72 69 64 67 65 07 61 6c   a62.wagbridge.al
0050  69 62 61 62 61 04 74 61 6e 78 c0 1a c0 2f 00 05   ibaba.tanx.../..
0060  00 01 00 00 01 2c 00 40 13 64 75 61 6c 73 74 61   .....,.@.dualsta
0070  63 6b 2d 6e 61 36 31 2d 6e 61 36 32 09 77 61 67   ck-na61-na62.wag
0080  62 72 69 64 67 65 07 61 6c 69 62 61 62 61 04 74   bridge.alibaba.t
0090  61 6e 78 03 63 6f 6d 03 67 64 73 0a 61 6c 69 62   anx.com.gds.alib
00a0  61 62 61 64 6e 73 c0 1a c0 68 00 1c 00 01 00 00   abadns...h......
00b0  00 1a 00 10 24 08 40 01 0f 00 00 00 00 00 00 00   ....$.@.........
00c0  00 00 01 e0 c0 68 00 1c 00 01 00 00 00 1a 00 10   .....h..........
00d0  24 08 40 01 0f 10 00 00 00 00 00 00 00 00 00 42   $.@............B
00e0  c0 68 00 1c 00 01 00 00 00 1a 00 10 24 08 40 01   .h..........$.@.
00f0  0f 10 00 00 00 00 00 00 00 00 01 43 c0 68 00 1c   ...........C.h..
0100  00 01 00 00 00 1a 00 10 24 08 40 01 0f 10 00 00   ........$.@.....
0110  00 00 00 00 00 00 01 7e c0 68 00 1c 00 01 00 00   .......~.h......
0120  00 1a 00 10 24 01 b1 80 20 00 00 10 00 00 00 00   ....$... .......
0130  00 00 00 36 c0 68 00 1c 00 01 00 00 00 1a 00 10   ...6.h..........
0140  24 01 b1 80 20 00 00 30 00 00 00 00 00 00 00 23   $... ..0.......#
0150  c0 68 00 1c 00 01 00 00 00 1a 00 10 24 08 40 01   .h..........$.@.
0160  0f 00 00 00 00 00 00 00 00 00 00 5a c0 68 00 1c   ...........Z.h..
0170  00 01 00 00 00 1a 00 10 24 08 40 01 0f 00 00 00   ........$.@.....
0180  00 00 00 00 00 00 00 9d c0 68 00 1c 00 01 00 00   .........h......
0190  00 1a 00 10 24 08 40 01 0f 00 00 00 00 00 00 00   ....$.@.........
01a0  00 00 01 70 c0 68 00 1c 00 01 00 00 00 1a 00 10   ...p.h..........
01b0  24 08 40 01 0f 00 00 00 00 00 00 00 00 00 01 8d   $.@.............

No.     Time           Source                Destination           Protocol Length Info
   4057 5828.286174    192.168.137.77        LAPTOP-JPYKT433.local UDP      75     48451 → clearvisn(2052) Len=33

Frame 4057: 75 bytes on wire (600 bits), 75 bytes captured (600 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2), Dst: LAPTOP-JPYKT433.local (0e:54:15:75:2c:77)
Internet Protocol Version 4, Src: 192.168.137.77 (192.168.137.77), Dst: LAPTOP-JPYKT433.local (192.168.137.1)
User Datagram Protocol, Src Port: 48451 (48451), Dst Port: clearvisn (2052)
Data (33 bytes)

0000  2c 61 01 00 00 01 00 00 00 00 00 00 05 75 6c 6f   ,a...........ulo
0010  67 73 05 75 6d 65 6e 67 03 63 6f 6d 00 00 01 00   gs.umeng.com....
0020  01                                                .

No.     Time           Source                Destination           Protocol Length Info
   4058 5828.296996    192.168.137.77        LAPTOP-JPYKT433.local UDP      77     56844 → clearvisn(2052) Len=35

Frame 4058: 77 bytes on wire (616 bits), 77 bytes captured (616 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2), Dst: LAPTOP-JPYKT433.local (0e:54:15:75:2c:77)
Internet Protocol Version 4, Src: 192.168.137.77 (192.168.137.77), Dst: LAPTOP-JPYKT433.local (192.168.137.1)
User Datagram Protocol, Src Port: 56844 (56844), Dst Port: clearvisn (2052)
Data (35 bytes)

0000  ac a0 01 00 00 01 00 00 00 00 00 00 07 70 6c 62   .............plb
0010  73 6c 6f 67 05 75 6d 65 6e 67 03 63 6f 6d 00 00   slog.umeng.com..
0020  01 00 01                                          ...

No.     Time           Source                Destination           Protocol Length Info
   4059 5828.302702    LAPTOP-JPYKT433.local 192.168.137.77        UDP      194    clearvisn(2052) → 48451 Len=152

Frame 4059: 194 bytes on wire (1552 bits), 194 bytes captured (1552 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: LAPTOP-JPYKT433.local (0e:54:15:75:2c:77), Dst: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2)
Internet Protocol Version 4, Src: LAPTOP-JPYKT433.local (192.168.137.1), Dst: 192.168.137.77 (192.168.137.77)
User Datagram Protocol, Src Port: clearvisn (2052), Dst Port: 48451 (48451)
Data (152 bytes)

0000  2c 61 81 80 00 01 00 05 00 00 00 00 05 75 6c 6f   ,a...........ulo
0010  67 73 05 75 6d 65 6e 67 03 63 6f 6d 00 00 01 00   gs.umeng.com....
0020  01 c0 0c 00 05 00 01 00 00 01 2c 00 21 05 75 6c   ..........,.!.ul
0030  6f 67 73 05 75 6d 65 6e 67 03 63 6f 6d 03 67 64   ogs.umeng.com.gd
0040  73 0a 61 6c 69 62 61 62 61 64 6e 73 c0 18 c0 2d   s.alibabadns...-
0050  00 05 00 01 00 00 00 bf 00 09 06 61 6c 6f 67 75   ...........alogu
0060  73 c0 12 c0 5a 00 05 00 01 00 00 00 3c 00 09 06   s...Z.......<...
0070  61 6c 6f 67 75 73 c0 33 c0 6f 00 01 00 01 00 00   alogus.3.o......
0080  01 11 00 04 2f f6 6d 6c c0 6f 00 01 00 01 00 00   ..../.ml.o......
0090  01 11 00 04 2f f6 6d 6d                           ..../.mm

No.     Time           Source                Destination           Protocol Length Info
   4060 5828.314578    LAPTOP-JPYKT433.local 192.168.137.77        UDP      226    clearvisn(2052) → 56844 Len=184

Frame 4060: 226 bytes on wire (1808 bits), 226 bytes captured (1808 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: LAPTOP-JPYKT433.local (0e:54:15:75:2c:77), Dst: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2)
Internet Protocol Version 4, Src: LAPTOP-JPYKT433.local (192.168.137.1), Dst: 192.168.137.77 (192.168.137.77)
User Datagram Protocol, Src Port: clearvisn (2052), Dst Port: 56844 (56844)
Data (184 bytes)

0000  ac a0 81 80 00 01 00 03 00 00 00 00 07 70 6c 62   .............plb
0010  73 6c 6f 67 05 75 6d 65 6e 67 03 63 6f 6d 00 00   slog.umeng.com..
0020  01 00 01 c0 0c 00 05 00 01 00 00 00 3c 00 2d 13   ............<.-.
0030  64 75 61 6c 73 74 61 63 6b 2d 6e 61 36 31 2d 6e   dualstack-na61-n
0040  61 36 32 09 77 61 67 62 72 69 64 67 65 07 61 6c   a62.wagbridge.al
0050  69 62 61 62 61 04 74 61 6e 78 c0 1a c0 2f 00 05   ibaba.tanx.../..
0060  00 01 00 00 01 2c 00 40 13 64 75 61 6c 73 74 61   .....,.@.dualsta
0070  63 6b 2d 6e 61 36 31 2d 6e 61 36 32 09 77 61 67   ck-na61-na62.wag
0080  62 72 69 64 67 65 07 61 6c 69 62 61 62 61 04 74   bridge.alibaba.t
0090  61 6e 78 03 63 6f 6d 03 67 64 73 0a 61 6c 69 62   anx.com.gds.alib
00a0  61 62 61 64 6e 73 c0 1a c0 68 00 01 00 01 00 00   abadns...h......
00b0  00 1e 00 04 cb 77 d6 7b                           .....w.{

No.     Time           Source                Destination           Protocol Length Info
   4061 5829.730365    192.168.137.77        LAPTOP-JPYKT433.local UDP      87     10287 → clearvisn(2052) Len=45

Frame 4061: 87 bytes on wire (696 bits), 87 bytes captured (696 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2), Dst: LAPTOP-JPYKT433.local (0e:54:15:75:2c:77)
Internet Protocol Version 4, Src: 192.168.137.77 (192.168.137.77), Dst: LAPTOP-JPYKT433.local (192.168.137.1)
User Datagram Protocol, Src Port: 10287 (10287), Dst Port: clearvisn (2052)
Data (45 bytes)

0000  52 75 01 00 00 01 00 00 00 00 00 00 09 67 6f 6f   Ru...........goo
0010  67 6c 65 61 64 73 01 67 0b 64 6f 75 62 6c 65 63   gleads.g.doublec
0020  6c 69 63 6b 03 6e 65 74 00 00 01 00 01            lick.net.....

No.     Time           Source                Destination           Protocol Length Info
   4062 5829.731079    LAPTOP-JPYKT433.local 192.168.137.77        UDP      196    clearvisn(2052) → 10287 Len=154

**Comment by kasnder** [comment]
Thanks for reporting this. It seems that only UDP packets are affected. Do you use a SOCKS5 proxy? What apps are affected?

**Comment by IL2P** [comment]
All apps seem affected. I am using US Cellular Samsung S9. 

One Ul version 2.5
Android version 10 
Baseband version G960USQS8FTKS 
Kernel version 4.9.186-19871035 #1 Wed Nov 25 03:37:42 KST 2020 
Build number QP1A.190711.020.G960USQS8FTK5 
SE for Android status Enforcing SEPF_SM-G960U_10_0022 Wed Nov 25 03:50:23 2020 
Knox version Knox 3.4.1 Knox API level 30 TIMA 4.0.0 
Service provider SW ver. SAOMC_SM-G960U_OYN_USC_QQ_0017 5059305555433498 USC/USC/USC
Security software version
    MDF v3.1 Release 5
    WLAN v1.0 Release 2
    VPN PP-MOD v2.1 Release 3.0.1
    ASKS v3.1 Release 20200806
    ADP v3.0 Release 20191001
    FIPS BoringSSL v1.4
    FIPS SKC v1.9
    FIPS SCrypto v2.2
    SMR Dec-2020 Release 1
Android security patch level December 1, 2020

"VPN" firewalls TrackerControl and NetGuard both have queries as blocked in the live in app log, that wireshark is still showing in it's log

**Comment by IL2P** [comment]
Edit: In trying to search this issue I saw some mention of app "Shelter". I have Shelter installed on my phone and have used it to isolate only 1 app to a "Work" profile. This one app is not among the apps tested

**Comment by kasnder** [comment]
Interesting that NetGuard and TC are affected. I know that umeng.com belongs to a Chinese company.  Does the problem persist if you enable “system apps” from the TC settings? Could you share a screenshot of the log, so I can see what app is affected?

**Comment by IL2P** [comment]
I enabled System Apps in settings and the did another small Wireshark capture after enabling TC. Screenshots, TC PCAP export, and Wireshark cap, were all done in the same run

https://drive.google.com/drive/folders/1yYyDfkMSjkvGbDjNkbCykNBWcw9jWB4x?usp=sharing

Let me know if this is what you are looking for or if I should do a more controlled test/else

**Comment by IL2P** [comment]
Thank you for the contributions you have made to protect privacy.

Rant: (Not towards you or this app). I decided I will reduce the big tech spyware in my life. The struggle is real! I have been unable to block Google Play Services and Samsung system apps on my phone. I believe they have granted themselves root access or other to bypass any non root blocking measures. They can't be uninstalled, closed, disabled, or permissions changed. I am getting more upset every day. Google turns on my microphone constantly (100+ times per day) even when I have "disabled" the google voice functions. Samsung calls home constantly and have granted their system apps nearly every system level access privacy privilege possible. AWS/Google/Facebook are getting a realtime stream of data from my phone. What kind of world have I found myself in? Who is fighting for my right to privacy? How is it legal to force spy apps down my throat and force me to use them against my will? Why has my choice been stripped away from me? Why am I angry to the point of physical sickness? Am I alone here? Why are my friends not disgusted? What is the best way to fight this? 

It feels like we are on the precipice of change now or dystopia forever. I want change NOW!

**Comment by kasnder** [comment]
Thanks for sharing this. I’ll try to investigate carefully over the weekend.

**Comment by kasnder** [comment]
Hi there! As promised, I looked into your issue. When looking at your network traffic, what you see seem to be DNS requests. These are not requests to the servers of tracker companies.

For example, this DNS requests to your router at IP address 192.168.137.1 looks up the domain `audio4-fa.scdn.co`:
```
No.     Time           Source                Destination           Protocol Length Info
      1 0.000000       192.168.137.77        192.168.137.1         UDP      77     43143 → clearvisn(2052) Len=35

Frame 1: 77 bytes on wire (616 bits), 77 bytes captured (616 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2), Dst: LAPTOP-ETJWHXL9.local (0e:54:15:75:2c:77)
Internet Protocol Version 4, Src: 192.168.137.77 (192.168.137.77), Dst: 192.168.137.1 (192.168.137.1)
User Datagram Protocol, Src Port: 43143 (43143), Dst Port: clearvisn (2052)
Data (35 bytes)

0000  9e dd 01 00 00 01 00 00 00 00 00 00 09 61 75 64   .............aud
0010  69 6f 34 2d 66 61 04 73 63 64 6e 02 63 6f 00 00   io4-fa.scdn.co..
0020  01 00 01                                          ...
```

Immediately afterwards, the router gives an answer: contact the domain `ipv4.scdnco.spotify.map.fastly.net` when an app wants to contact the domain `audio4-fa.scdn.co`:
```
No.     Time           Source                Destination           Protocol Length Info
      2 0.038888       192.168.137.1         192.168.137.77        UDP      141    clearvisn(2052) → 43143 Len=99

Frame 2: 141 bytes on wire (1128 bits), 141 bytes captured (1128 bits) on interface \Device\NPF_{B334E7E7-7FF2-4B64-A567-712128244301}, id 0
Ethernet II, Src: LAPTOP-ETJWHXL9.local (0e:54:15:75:2c:77), Dst: ea:8f:ff:16:ce:e2 (ea:8f:ff:16:ce:e2)
Internet Protocol Version 4, Src: 192.168.137.1 (192.168.137.1), Dst: 192.168.137.77 (192.168.137.77)
User Datagram Protocol, Src Port: clearvisn (2052), Dst Port: 43143 (43143)
Data (99 bytes)

0000  9e dd 81 80 00 01 00 02 00 00 00 00 09 61 75 64   .............aud
0010  69 6f 34 2d 66 61 04 73 63 64 6e 02 63 6f 00 00   io4-fa.scdn.co..
0020  01 00 01 c0 0c 00 05 00 01 00 00 00 0c 00 24 04   ..............$.
0030  69 70 76 34 06 73 63 64 6e 63 6f 07 73 70 6f 74   ipv4.scdnco.spot
0040  69 66 79 03 6d 61 70 06 66 61 73 74 6c 79 03 6e   ify.map.fastly.n
0050  65 74 00 c0 2f 00 01 00 01 00 00 00 1e 00 04 97   et../...........
0060  65 fa f8                                          e..
```

**Comment by kasnder** [comment]
This is also related to #155

**Comment by kasnder** [comment]
I'll investigate this further in #163. I think there's a way how to do this better -- and also better than NetGuard. By blocking these things by default.
