### ISSUE TITLE
[BUG] TrackerControl breaks DNS resolution if connected to a 10.1.10.0/24 network

### ISSUE THREAD

**Issue by metronidazole** [OxfordHCC/tracker-control-android#159]
Edit: Looking at your code, it seems the VPN interface uses a 10.1.10.0/24 network. 

Can you please change it to something more random so it doesn't conflict if a user uses the same subnet e.g. 10.157.234.1/24

-----------------------
My device is connected to a wifi network and receives the following IP configuration via DHCP:
IP: 10.1.10.52/24
DNS resolver: 10.1.10.1

I'm using android 11 with calyx os.

If tracker control is enabled, all apps on my phone break as they cannot perform DNS resolution. e.g. searching is broken in firefox, Nothing shows in TC even if traffic log is enabled. However I can still access e.g. http://1.1.1.1 

On the otherhand, if I change my phone to use a static IP configuration with a public DNS resolver e.g. 1.1.1.1 or 8.8.8.8, everything works fine, even if TC is enabled. 

I have tried the following settings
- strict and non-strict mode (no difference)
- monitoring for a test app enabled and disabled (no difference)
- always on VPN is disabled
- private DNS is disabled
- battery optimisation for TC is off

**Comment by kasnder** [comment]
Thanks for pointing this out. Would you be able to make a pull request?

**Comment by kasnder** [comment]
Maybe, this is something that could be added as a setting to TC?

**Comment by kasnder** [comment]
Also, you could potentially try use a different local DNS resolver? Nebulo is a great tool.

**Comment by metronidazole** [comment]
DNS resolution is not the only thing broken. It also breaks access to the local network. 

I have create a pull request which fixes this.

> Maybe, this is something that could be added as a setting to TC?

That would be ideal but I'm not an android dev.

**Comment by kasnder** [comment]
Have you tried changing the IP address from the TC settings?

**Comment by metronidazole** [comment]
Hmm, I did not know that feature was already built in, hence why I opened this issue. Since that is the case, the PR is not needed then.
