### ISSUE TITLE
Move api.mapbox.com into separate category (uber app)

### ISSUE THREAD

**Issue by metronidazole** [OxfordHCC/tracker-control-android#160]
With the uber android app, one of the essential components connects to api.mapbox.com which is listed under uncategorised with tracker control. The issue is that to unblock that category, you have to unblock two trackers which are also uncategorised (client-analytics.braintreegateway.com, 7336.engine.mobileapptracking.com)

It would be nice if api.mapbox.com was in it's own separate category, or at the very least, under essential.

**Comment by kasnder** [comment]
Good question. Will add this ASAP!

**Comment by kasnder** [comment]
Fixed now. Download latest version from GitHub

**Comment by metronidazole** [comment]
Thanks
