### ISSUE TITLE
Less Notifications On Device

### ISSUE THREAD

**Issue by theappuser** [OxfordHCC/tracker-control-android#162]
Would welcome a way to either reduce the 2 notifications for this to just 1 or none. The first notification is for the VPN and the second one is saying, "TrackerControl" Checking trackers. This doesn't leave a lot of room for other notifications and the screen seems cluttered already.

I do love the app. It works very well.

**Comment by kasnder** [comment]
What Android version do you use? In most versions, you should be able to hide the notification from the settings of your Android system.

Unfortunately, the notification is necessary to run TrackerControl in the background.

**Comment by theappuser** [comment]
I am running Marshmallow on an older Samsung Galaxy.

On February 7, 2021 8:36:15 AM EST, Konrad Kollnig <notifications@github.com> wrote:
>What Android version do you use? In most versions, you should be able
>to hide the notification from the settings of your Android system.
>
>Unfortunately, the notification is necessary to run TrackerControl in
>the background.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OxfordHCC/tracker-control-android/issues/162#issuecomment-774675608

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by theappuser** [comment]
I did disable the notifications so now I only have the VPN notification showing. Thanks

On February 7, 2021 8:36:15 AM EST, Konrad Kollnig <notifications@github.com> wrote:
>What Android version do you use? In most versions, you should be able
>to hide the notification from the settings of your Android system.
>
>Unfortunately, the notification is necessary to run TrackerControl in
>the background.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/OxfordHCC/tracker-control-android/issues/162#issuecomment-774675608

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
