### ISSUE TITLE
TrackerControl won't list trackers (CalyxOS 11)

### ISSUE THREAD

**Issue by GitGangGuy** [OxfordHCC/tracker-control-android#165]
I installed TrackerControl from the official f-droid repo on my Pixel 5 running CalyxOS (AOSP 11) and it won't list trackers of apps I open via TrackerControl or like I normally would over my launcher. I have turned off Private DNS, turned on the switch in TrackerControl, enabled strict blocking by default and set the VPN connection through TrackerControl to always-on. Traffic logging works (pretty nifty), but the main feature (blocking trackers by default) doesn't seem to work, regardless of what I do. The country map also doesn't show anything.  
Is this a known issue? Is there a way for me to provide more data to make diagnosis easier? Are there alternative apps I can use in the meantime with a similar feature set? (NetGuard seems to only block internet access per app in the free version which I can already do more easily over the android app settings and Blokada doesn't have a traffic log)

**Comment by GitGangGuy** [comment]
I just restarted my phone and now everything is working as expected. Thanks!

**Comment by kasnder** [comment]
Great that you solved it. Sometimes it take some time for changes to be effective!
