### ISSUE TITLE
[question] how does tracker control affect battery usage?

### ISSUE THREAD

**Issue by WPFilmmaker** [OxfordHCC/tracker-control-android#172]
First of all thank you for this great app!

I have seen the ticket regarding ram usage, and I have seen #44, netguards claims to reduce battery usage, but I noticed tracker control asks for disabling battery optimizer and to work it has to be always on so I am wondering does tracker control in general increase battery usage? Usually all privacy-related tools come with some trade off and I wouldn't mind losing a 1 or 2% battery for increased privacy but two digits loss wouldn't be nice, do you know anything about it?

**Comment by kasnder** [comment]
Most users report a very small impact on battery use.
