### ISSUE TITLE
1 tracker inside TrackerControl !

### ISSUE THREAD

**Issue by iiitomo** [OxfordHCC/tracker-control-android#174]
Surprisingly, ClassyShark3xodus detects one tracker (188org.acra) inside TrackerControl , see attached screenshot.

![Screenshot_20210323-150731_ClassyShark3xodus](https://user-images.githubusercontent.com/58949423/112159894-e88b0d80-8be9-11eb-9af2-13bd7f3ae96f.png)

**Comment by kasnder** [comment]
This has been discussed in #83, and is discussed in the privacy notice <https://github.com/OxfordHCC/tracker-control-android#privacy-notice>: "TrackerControl uses the ACRA plugin. This is considered to be a 'good' tracker. It's open-source, and could be used to collect crash reports automatically to a server–TrackerControl DOES NOT do this. Instead, the user must app report crashes manually, via e-mail. ACRA shows a dialog to do this in TrackerControl."

**Comment by iiitomo** [comment]
ok, thanks for the explanation.
