### ISSUE TITLE
Two apps shows strange behavior since using tracker control

### ISSUE THREAD

**Issue by WPFilmmaker** [OxfordHCC/tracker-control-android#175]
I am experiencing two issues one with redreader (https://github.com/QuantumBadger/RedReader/issues) and one with webapps (https://github.com/tobykurien/WebApps/issues) since I started using tracker control.

RedReader when I click on external links (normally they would open in the internal browswer which I think is webkit) it does not work and

Wepapps when I try to open the app it crashes.

I disabled the tracking protection on both apps, restarted the phone but the issue still occur.

I suspect something is getting blocked hence the unexpected behavior. However since I disabled the protection on both apps, why are connections still blocked? I thought it might be that I am blocking a needed connection on another app, but then I thought why does it affect also disabled apps? (I think with tracker control you can allow connections to certain domains in one app but block them in another right?)
Any clue?
I have trackercontrol 2021.02.06-fdroid, phone is motog7 power Android 10. 

edit: after restarting phone and waiting a while apps now do work, is it a normal behavior or?

**Comment by kasnder** [comment]
Do you have blocking of system apps enabled? If so, try to disable this setting and let me know if the issue persists.

**Comment by WPFilmmaker** [comment]
You mean advanced options-Manage system apps?
If yes, no it is disabled.

Any way I can provide more information?

**Comment by kasnder** [comment]
Something you can try, is disabling monitoring for these apps.

**Comment by WPFilmmaker** [comment]
@kasnder indeed they are disabled and worked fine, I was just wondering if it was a normal behavior that I had to restart phone in order to make the apps working again, if it is I can close this ticket, if not you might want to check.

**Comment by kasnder** [comment]
Oh okay. It often works if you just "force stop" the app, or remove it from the recently opened apps.
