### ISSUE TITLE
Publishing the app on F-Droid

### ISSUE THREAD

**Issue by Atrate** [OxfordHCC/tracker-control-android#18]
Once the app is more stable (or just now), I would recommend publishing it to the F-Droid FOSS app store, this can help it gain popularity amount the FOSS community and make it easily accessible for people living without Gapps (as I presume publishing it on Google's Play Store is also on the roadmap).

**Comment by kasnder** [comment]
Very good point. The app used to be very unstable, but it’s getting much better recently. I’ll share it soon on F-Droid. Thanks for suggesting this!

**Comment by kasnder** [comment]
Update: I've cleaned up the code, and added a more up-to-date blocklist (Disconnect). If no major issues pop up, the app will be released soon on F-Droid.

If any errors pop up for you, let me know!

**Comment by kasnder** [comment]
The app is currently under review and will be released as soon as this is over!

**Comment by kasnder** [comment]
With the help of great volunteers, the app has now been accepted and will be on F-Droid shortly!

Also, thanks for making this suggestion in the first place @Atrate.
