### ISSUE TITLE
Readme Translation

### ISSUE THREAD

**Issue by another-sapiens** [OxfordHCC/tracker-control-android#181]
Hi there! 
After translating the app itself, I couldnt help but wonder if there was a way to translate the app's description on F-Droid. I've seen other apps do it, but I'm new to this and don't know how to do it.
Any ideas?

**Comment by kasnder** [comment]
I hadn't thought about this before, but this would indeed be possible.

If you look in this folder, there's a German and US English translation: https://github.com/OxfordHCC/tracker-control-android/tree/master/fastlane/metadata/android

It'd be possible to create a new folder "es" and add translated files "full_description.txt" and "short_description.txt".

**Comment by kasnder** [comment]
You'd then have to make another pull request.

**Comment by kasnder** [comment]
Alternatively, I'll investigate if it's possible to add this to Crowdin

**Comment by kasnder** [comment]
Update: thus is possible with Crowdin. I need to add something like this file https://framagit.org/tom79/fedilab/blob/develop/crowdin.yml

**Comment by another-sapiens** [comment]
Hello!
I've just translated it. I can manage with the .xml file, but Crowdin may be a good idea if more people want to collaborate. 

I don't know much about files and whatnot, though, I'm better at translating only know the very basics about this stuff. How can I help you on this one? 
Or where can I learn about it?
