### ISSUE TITLE
Language option

### ISSUE THREAD

**Issue by yetanotherfossman** [OxfordHCC/tracker-control-android#191]
First of all, thanks for this software!

Looks like this app is translated into other languages, but there's no option for change it on settings. This would be very helpful because the app not always recognize the language correctly.

**Comment by kasnder** [comment]
What language doesn’t work for you?

**Comment by yetanotherfossman** [comment]
Yes, exactly.

**Comment by another-sapiens** [comment]
Can confirm the language defaults to English, at least in the `es-AR` locale.

**Comment by another-sapiens** [comment]
Jackpot! I believe it will only detect tte language if it coincides with the locale in the code, and not other locales for that particular language. Tested out the Spanish (Spain) locale and it worked like a charm.

Also, I should point out that my translation falls more into the `es-AR` category, but used `es-ES` as I didn't know the difference at the time.

**Comment by yetanotherfossman** [comment]
@another-sapiens Can confirm, when I changed my system language to es-ES it worked :)

**Comment by another-sapiens** [comment]
I just created a pull request with a possible fix. Fingers crossed!

**Comment by kasnder** [comment]
Thanks for the pull request. As I explained there that "the issue is with the translation service CrowdIn. I'll try to change the configuration of this service so that languages will be correct again."

**Comment by kasnder** [comment]
Ok, I've figured it out. The changes will go online in the next release.

https://github.com/OxfordHCC/tracker-control-android/commit/8688bb312cf378243b1c113eebc294d5e0958ce7

**Comment by another-sapiens** [comment]
Oops, I thought it had to do with something else (it made sense in my head).

Thank you for the fix!
