### ISSUE TITLE
Tracker Control crashes when opening a specific app

### ISSUE THREAD

**Issue by WPFilmmaker** [OxfordHCC/tracker-control-android#193]
I updated to version  2021.05.05 (the latest available on f-droid) and while enjoying the new domain-based block/allow, the app crashed and two things happened:

1 all known companies in the apps reverted to 'last week' (but if you click in the apps you can see the selected domains being blocked so the error is just about on the main page)

2 a specific app (which I would rather not mention here due to privacy) makes tracker control crash whenever from the main page I press on it to see what is being blocked. Once it crashes a message appears where I can send an email to the devs with what happened. Does it contain any log or what? I didn't send anything as I wasn't sure what the message would contain.

Is there a way I can tell you the name of the app privately?(maybe through private message or email?

**Comment by kasnder** [comment]
Try again with the latest version of TC (from today) if the crash persists. I tried to fix it.

Also, thanks for reporting about trackers not being shown. I’ll fix this ASAP! Blocking functionality shouldn’t be affected, since this is handled separately from the UI.

**Comment by WPFilmmaker** [comment]
I think f-droid takes a few days to offer new versions so I will wait a few days for the latest version and report if issues persist!
About the second issue yes it seems that blocking is not affected but I am glad you are sorting it out!

Thanks to you and the other devs for this great app!

**Comment by yetanotherfossman** [comment]
I'm using the last version in F-Droid and also experimented crashes, but it only happens when I tap in system apps. Looks like it's because the new ClassyShark-like tracker detection can't handle system apps properly (ClassyShark3xodus have this issue too).

However, I tried the new version in Github and it's fixed. So thanks for that! I just have to wait until it comes to F-Droid.

**Comment by kasnder** [comment]
I had a closer look @WPFilmmaker at the second issue about trackers only shown for the past week. You should be able to change this by changing the sort order from the top bar in the main screen. Does this fix your issue, or are you talking about yet another issue?

**Comment by WPFilmmaker** [comment]
@kasnder I hadn't thought about that as I hadn't touched the settings but you were right going back to my previous settings solve this. For whatever reason the updated changed the settings.

just for reference the app that causes troubles for me is not a system app.

**Comment by kasnder** [comment]
@WPFilmmaker The latest update (on GitHub) fixes a range of crashed related to the static detection. Hope this works for you!

**Comment by WPFilmmaker** [comment]
@kasnder Hello I just updated Tracker Control from f-droid (2021.05.14-fdroid), unfortunately the app still make Tracker Control crash :/

How can i privately tell you whats the app in question so you can try and replicate?

I noticed when I open the app the tracker libraries section shows a loading circle but then the app crashes :/

**Comment by kasnder** [comment]
> How can i privately tell you whats the app in question so you can try and replicate?

Sorry about that. Send me a message at hello@trackercontrol.org

**Comment by WPFilmmaker** [comment]
@kasnder have you received my email with the crashlog?

**Comment by kasnder** [comment]
> @kasnder have you received my email with the crashlog?

Yes! Does the new version work for you?

**Comment by WPFilmmaker** [comment]
@kasnder Great! I hadn't receive any reply so I wondered ;) I will be waiting for f-droid to update and report.

**Comment by kasnder** [comment]
> @kasnder Great! I hadn't receive any reply so I wondered ;) I will be waiting for f-droid to update and report.

Seems like I was too busy fixing bugs.. Sorry!

**Comment by WPFilmmaker** [comment]
@kasnder it fixes it!
