### ISSUE TITLE
Add a custom DNS/VPN option out

### ISSUE THREAD

**Issue by PoorPocketsMcNewHold** [OxfordHCC/tracker-control-android#2]
Hi there,
One issue, when using your tool, is that it use the VPN functionality of the phone, in order to have access to the different internet communications all the apps on the devices does, and, be able to tag the tracker activity.
However, by doing so (and due to how it works in Android 9) :
- This make me unable to use my custom private DNS settings (Especially in this case, in which i use to block some already known specific trackers sources, and other adwares/malware sources)
- This also make me unable to use an another VPN connection (Pretty logical, since it allows only one VPN application to be added).
I don´t really know if how possible it would be to actually implement a basic openvpn capacity in order to redirect all the connections to the specified VPN, but i suppose being able to redirect all the traffic to a dedicated custom DNS should be implementable. 
Implementing DoH or DoT would be ideal, but implementing some custom settings for an IPV4 and IPV6 address should be enough.

**Comment by kasnder** [comment]
Thank you for your feedback. Private DNS is indeed not supported at the moment, since the tracking detection relies on monitoring contacted tracker domain names.

Can you clarify your suggestion to me a little bit. Are you suggesting to implement Private DNS within TrackerControl? Setting a normal DNS from the system settings should be possible regardless.

**Comment by PoorPocketsMcNewHold** [comment]
> Are you suggesting to implement Private DNS within TrackerControl?

Yes.
Basically :
```
Android -----------> Private DNS feature from Android --------------> Internet connection.
Android -----------> Custom VPN ----------------------------------------> Internet connection.
```
This is how you proceed to use DoT (Dns Over Tls) or use a VPN app.

However, by using Tracker-control  : 
```
Android ------------>Tracker Control VPN ----------|   Private DNS  | -----------> Internet.
                                                                            |                         |
                                                                            |--------------------|

Android ------------>Tracker Control VPN ----------------------------------------> Internet.

                        _Custom VPN not being used_
```

**Comment by kasnder** [comment]
So, you'd like to be able to set a DNS server within TrackerControl? That's a brilliant suggestion, thanks!

**Comment by kasnder** [comment]
I’ve been investigating a bit. It won’t be possible for me to add Private DNS. Yet, the next release will allow you to set a custom (non-private) DNS from the app settings, which I hope will help.

**Comment by kasnder** [comment]
New release is online now. This should fix your issue.
