### ISSUE TITLE
Support secure DNS

### ISSUE THREAD

**Issue by laurentlbm** [OxfordHCC/tracker-control-android#201]
At the moment, you can set custom DNS in the application, but it's IP-based. It would be great to be able to specify a DoH or DoT endpoint.

**Comment by kasnder** [comment]
You already can set up Nebulo with TrackerControl, and thereby get secure DNS. :)

**Comment by kasnder** [comment]
Use the port forwarding functionality. The set-up is similar as for NetGuard.

**Comment by laurentlbm** [comment]
Thanks, that works great. I had never heard of Nebulo before.

**Comment by login22rvp** [comment]
Try Invizible with Tracker control for DoH. It superb

**Comment by Inrumpo** [comment]
After I learned that one has to turn off private (encrypted DoT/DoH) DNS to be able to use TrackerControl, I was slightly bummed. It feels like getting one privacy improvement by giving up another. I want to have both. That's how I found this topic.

Yes, using [Nebulo](https://git.frostnerd.com/PublicAndroidApps/smokescreen) seems to work: Now I can use encrypted DNS _and_ TrackerControl at the same time. For those coming here and wondering _how_ to do this: I followed [this article](https://git.frostnerd.com/PublicAndroidApps/smokescreen/-/blob/master/docs/NONVPNMODE.md). Use the guide for NetGuard; the setup is identical.

I'm still of the opinion that this situation is not ideal. TrackerControl is a simple tool for non-techy people who want to improve their privacy. They're not going to follow GitHub issues and daisy-chain apps by port-forwarding TrackerControl back to their local device.

Is there a way to integrate this "Nebulo trick" into TrackerControl or somehow enable a private encrypted DNS solution to make this easier for the non-techy user? At least IMO the user should be informed what the consequence of giving up private DNS is and maybe be pointed to this workaround.

**Comment by kasnder** [comment]
I agree it's not ideal. I've been considering implementing a simpler setup of the port forwarding, and would appreciate help with this.

**Comment by mklopp** [comment]
I have the same setup running with TrackerControl and port forwarding DNS traffic into Nebulo so I can use DoT. 
Now I had to disable monitoring for my browser app, as it is not working (also stated within TC that you have to disable it for browsers to work) and ran into the issue that DNS queries from said browser would not get routed into Nebulo. As I understand the port forwarding is only applied to monitored apps and traffic from non monitored apps is just passed through. Is that correct? Is there any way to apply port forwarding to all traffic that passes through TC?

**Comment by Inrumpo** [comment]
> Is that correct?

That is an interesting find!

I did a quick test with my browser _not_ monitored through TrackerControl. You're right, the DNS specified in Nebulo won't be used in this case. That's another bummer.

On the other hand:
I did a second quick test. This time I had TrackerControl monitor my browser. Now the secure DNS is used as expected. I do not experience any drawbacks. My browser app is still working fine. Therefore: Why not just leave it that way?

**Comment by mklopp** [comment]
Because for me it does not work like that. When I have monitoring activated for my browser and try to access reddit.com for example the site won't load. Looking into the traffic log I can see that e.reddit.com was blocked. Though it isn't mentioned in the monitoring page of the browser.

**Comment by karolyi** [comment]
> I have the same setup running with TrackerControl and port forwarding DNS traffic into Nebulo so I can use DoT. Now I had to disable monitoring for my browser app, as it is not working (also stated within TC that you have to disable it for browsers to work) and ran into the issue that DNS queries from said browser would not get routed into Nebulo. As I understand the port forwarding is only applied to monitored apps and traffic from non monitored apps is just passed through. Is that correct? Is there any way to apply port forwarding to all traffic that passes through TC?

You can still use TC with the browser, just turn off any blocking and you'll get the same behavior, but with DNS requests routed through TC.

I use dnscrypt+invizible pro, works like a charm.

**Comment by js-d-coder** [comment]
Please support secure DNS natively for easy setup.
Secure DNS is a must for privacy when the user is travelling and uses public Wifi.

**Comment by Nitrowing** [comment]
I have to use a VPN but this disables TC and vice versa.
