### ISSUE TITLE
No notifications with some apps, when TC is ON

### ISSUE THREAD

**Issue by mlsem** [OxfordHCC/tracker-control-android#212]
Even if i am not blocking trackers, i do not receive notifications with some apps.

Examples : 

Use case01 :  
1. I kill my Signal messenger app
2. I ask some one to send me a message
3. I do not receive any
4. When i open signal app, I start receiving messages.

UseCase 02 : 
When I put  TC in "Pause" , I receive all notifications

**Comment by kasnder** [comment]
Do you have blocking system apps enabled?

**Comment by mlsem** [comment]
@kasnder  blocking is not enabled in TC.

**Comment by kasnder** [comment]
> @kasnder blocking is not enabled in TC.

Thanks for confirming. I'd recommend disabling 'monitoring' for Signal.

**Comment by mlsem** [comment]
> > @kasnder blocking is not enabled in TC.
> 
> Thanks for confirming. I'd recommend disabling 'monitoring' for Signal.

I tried already andeven if I disable monitoring for signal I  still not getting signal notifications

**Comment by kasnder** [comment]
If you have 'monitoring of system apps' disabled and monitoring of Signal also disabled, I think the only option left is resetting the settings of TC.

**Comment by absoluteinc** [comment]
Try allowing the 'essential' for android system, android system webview, and google play services. Some apps will have your incoming messages/notifications go through these services. I had the same issue and through tinkering and trial and error, allowing the essential for these got rid of all my problems.

**Comment by mlsem** [comment]
I confirm that I need to allow "essential" in google play services in order to got notifications from signal and other apps, Thanks @absoluteinc , we can close this issue , Thanks to all @kasnder and @absoluteinc .
