### ISSUE TITLE
imap.gmail.com listed as "social" rather than essential

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#214]
In my phone email client I noticed it was complaining about server errors.  I recently stopped using the gmail app and went to aquamail.   I checked android permissions and then I check trackercontrol which is when I noticed that "imap.gmail.com" is listed under social along with facebook as opposed to under essential.  I'd argue if you actually want to access gmail from a third party client  you have to use imap.gmail.com therefore it's essential.  smtp.gmail.com might be a similar issue for sending mail.

**Comment by kasnder** [comment]
Absolutely agree! :) I'll fix this.

**Comment by kasnder** [comment]
I've fixed this now, and it'll be part of the next update.
