### ISSUE TITLE
TrackerControl does not do anything despite detecting trackers

### ISSUE THREAD

**Issue by sbstn87** [OxfordHCC/tracker-control-android#220]
Hi,

I am afraid that TrackerControl does not do anything on my phone. It detects tracker libraries (and a lot of them as shown on the screenshot), but there is no option to block them. The same situation is for every app, with an exception of RedReader, where is it shown that the app connects to Reddit (as it is a Reddit app) and I can unblock the connection.

In the advanced options I have the Domaind-based Blocking enabled.

Is this a normal situation? If not, what can be the problem?

![Screenshot](https://user-images.githubusercontent.com/37237675/124142478-c5d68380-da79-11eb-9176-9fbcc8f266a3.png)

**Comment by sbstn87** [comment]
I got to the root of the problem. I have been using a custom DNS (via the Invizible Pro app) and TrackerControl does not work with it. Any ideas how to make them work together?

**Comment by kasnder** [comment]
Is this the version from the PlayStore?

**Comment by kasnder** [comment]
Did you disable Private DNS from your Android settings?

**Comment by kasnder** [comment]
Sometimes, this takes a while.

**Comment by sbstn87** [comment]
This is the F-Droid version. No, the Private DNS mode is set to automatic. Should it be disabled?

**Comment by sbstn87** [comment]
Ok, after disabling it, trackers are detected and can be blocked. Thank you.
