### ISSUE TITLE
Add warning for activation requesting organisation names

### ISSUE THREAD

**Issue by ph00lt0** [OxfordHCC/tracker-control-android#232]
When enabling the traffic log, the app starts connecting to ipinfo.io. This is should imho be considered a tracker itself. 
It would be useful if users get a warning when trying to enable this lookup feature. Inside the app it is unclear that you will be sending requests to ipinfo.io. I only discovered this because of my network firewall.

Related: https://github.com/privacytools/privacytools.io/issues/2333

**Comment by kasnder** [comment]
Agree! I'm considering removing this functionality altogether, see #234 

However, there's benefit for users in trying to understand more about domains that are not on the tracker database.

**Comment by kasnder** [comment]
I've now added a dialog in commits 39f1ad54e89118dc7b1fb224772532c484f6f343 and 0d0f64f4547f8de62eaf0631aa40e67bfd6379b2
