### ISSUE TITLE
Nothing comfortable as netguard

### ISSUE THREAD

**Issue by Safetysurfer** [OxfordHCC/tracker-control-android#238]
1.can't restrict all apps data connection at once !
2.can't differenciate apps like system apps, apps with no data, disabled apps, user apps
3.no option to lockdown traffic
4.many more....
I like trackercontrol get this feaures and get more likely to netguard !

**Comment by kasnder** [comment]
1. Tracking is restricted by default.
2. Blocking tracking in system apps is not recommended because it can lead to unexpected behaviour.
3. and 4. Sorry. Trying to keep things simple.
