### ISSUE TITLE
Confused by block toggle switch interface

### ISSUE THREAD

**Issue by markwmuller** [OxfordHCC/tracker-control-android#241]
Whenever I download a new app, it takes me a minute to figure out the TC interface again. 

I think there are two problems I have: 
1. The switch for "monitoring" and "internet access" is to turn it on (i.e. toggle on means this function is allowed / on); however the switches for "Analytics" etc. have the opposite meaning (toggle on means this function is NOT allowed / off). 
2. The text "block" is on the left-hand side, i.e. when the switch is to the left (off) it is closer to "block", but the meaning is that it is not blocked. 

Perhaps the language can be changed to "allow", so that all switches have the meaning "Toggle on means this feature is on". Furthermore, I suggest removing the label on the side of the switch (or perhaps putting the label on the other side? Dunno how the GUI layout works). 

Thanks for the App, it seems great!

**Comment by kasnder** [comment]
Thanks for this. I know the current design isn't perfect. Currently, the idea is that all switches such that they are enabled by default. If you want to alter the default setting you turn it in the other direction (swipe toggle to the left).

The other problem is that I find Android's switch design just not intuitive. Usually, the design language means that toggles describe enabling things. So, if the toggle saying "block" is on, this means that blocking is enabled. However, this design language of Android is not at all intuitive. I really wish there'd be a better way..
