### ISSUE TITLE
Battery drain caused by hanging from blocked URL in the hosts file

### ISSUE THREAD

**Issue by daankata** [OxfordHCC/tracker-control-android#243]
When using NetGuard, with an imported hosts file, and I try to access a blocked domain it immediately blocks it and does not let me access it. But when using TrackerControl, with the same imported hosts file like in NetGuard, and I try to access the same domain, it does not block it immediately, but instead hangs and tries to connect to the domain for more than 4 minutes, after which shows "This site can't be reached. Domain took too long to respond". Both NetGuard and TrackerControl work and do actively block the desired domain from the hosts file, but TrackerControl does not block it immediately and instead hangs.

I think this is the primarily reason why TrackerControl is draining my battery by 23%, and NetGuard isn't. Is there an option to immediately block the domain in the hosts file without trying to connect to it?

**Comment by kasnder** [comment]
Wow, you rightly spotted that TC handles host lists somewhat differently! NetGuard blocks hosts on a DNS basis, while TC blocks hosts on a packet basis.

What specific app are you having problems with?

The battery impact of TrackerControl is usually really small. The code is really simple, and CPU and RAM usage is neglible, on most devices.

**Comment by daankata** [comment]
Oh, I see. And indeed, managing hosts lists on a per-app basis is more intuitive and allows for greater control. Thanks for the clarification.

I cannot really tell at the moment which app could be causing this, or is it system wide from all apps combined. I have also enabled system apps and have over 700k hosts rules which can also be contributing to the problem. Also, the app is not always causing excessive battery drain, e.g. today TrackerControl has been used for 15h and has drained only 6% of my battery. I will update this issue if I spot that there is a particular app that is causing the battery drain.

I really love the project! Can you consider some kind of a sponsor option, preferably through Liberapay?

**Comment by kasnder** [comment]
Please keep me posted!

I think some users reported that battery use might be wrongly attributed to TC, since the app necessarily runs in the background all the time.

And no sponsoring available, but I appreciate the offer!
