### ISSUE TITLE
'Waiting for event' notification with TC switched off

### ISSUE THREAD

**Issue by IScoffedTheLaw** [OxfordHCC/tracker-control-android#245]
I only discovered the app through F-Droid a few days ago and don't have the time to tinker with it now, so I've kept it switched off. Regardless of that, I am still recieving notifications that it is 'Waiting for event' a couple of times per hour. 

If the service is switched off, it shouldn't be doing anything. Checked settings and found nothing relating to this, so I am assuming it is a bug.

**Comment by kasnder** [comment]
This is related to the way Android handles long-term notifications.

If you use Spotify, you'll notice that this app sometimes does the same.

I recommend disabling TC notifications in that case.
