### ISSUE TITLE
Migrate/give option to change supplementary blocking file to oisd and add the ability to use ABP syntax.

### ISSUE THREAD

**Issue by ZycatForce** [OxfordHCC/tracker-control-android#253]
https://oisd.nl/ is currently the blocklist that a lot of other DNS filters use for a good reason, it prioritizes internet experience first (zero false positives/breakages) and an ad/tracker/etc blocking as second. Also, the faq for oisd states that abp syntax is better than hosts.

**Comment by kasnder** [comment]
Sounds like a great project. TrackerControl tries to be educational and give users full control and transparency. That's why it aims to block all trackers by default.
