### ISSUE TITLE
Root support

### ISSUE THREAD

**Issue by WorkingFancy** [OxfordHCC/tracker-control-android#255]
I don't know if it can be done or not 
But i use a vpn service so i can't use trackercontrol at the same time it would be nice if i can use them at the same time

**Comment by Erifxof** [comment]
French lingue ,please

**Comment by Erifxof** [comment]
Je repond en français,veuillez ,m'excuse, tout a portant ,a votre connaissance que : le français,l'arabe ,langueVIVANTE. bref ,veuillez nous eclairé sur methode root , soutenez vous le root, le root benefique ou non ,le root pourqoui applique par des applis chinoise ,user ,q'il soit applique par des applis non chinoise c'est mieux ,attention aux applis chinoise tres dangereuse

**Comment by Erifxof** [comment]
Veuillez nous explique en français ,la bonne methode ROOT

**Comment by Erifxof** [comment]
Merci,j'ai termine,j'attend votre reponse ,bonne reponse

**Comment by Erifxof** [comment]
Erifxof32@gmail.com.j'attend votre reponse,vive le githu

**Comment by kasnder** [comment]
There won't be root because TC aims to be accessible to all users.

**Comment by aviallon** [comment]
@kasnder how about multi-backend support?
I believe we can do nftables filtering on Android.
Surely using root to enable such a rule instead of using the VPN trick would work.
