### ISSUE TITLE
Relation to DuckDuckGo's mobile app tracking?

### ISSUE THREAD

**Issue by vadi2** [OxfordHCC/tracker-control-android#257]
I see DDG recently announced https://spreadprivacy.com/introducing-app-tracking-protection - does it have any relationship to TrackerControl?

**Comment by kasnder** [comment]
> I see DDG recently announced https://spreadprivacy.com/introducing-app-tracking-protection - does it have any relationship to TrackerControl?

The app seems to have indeed similar aims, though DDG app is arguably easier to use (it is less intrusive than TC and leads to less breakage) and focuses less on exposing ALL tracking (as TC does).

I've had the pleasure of talking to some of the engineers behind it and they seem to have good intentions, but the development of this system has been completely independent from TrackerControl.
