### ISSUE TITLE
Why its in Java and not in kotlin

### ISSUE THREAD

**Issue by hellosagar** [OxfordHCC/tracker-control-android#258]
Just curious to know why you started it in Java even tho this project is started in late 2019

**Comment by kasnder** [comment]
> Just curious to know why you started it in Java even tho this project is started in late 2019

Java seemed more widely used than Kotlin when the project started, and even outside the Googleverse.

Do you disagree?

**Comment by Erifxof** [comment]
Go men !

Le mar. 30 nov. 2021 23:16, Konrad Kollnig ***@***.***> a
écrit :

**Comment by hellosagar** [comment]
@kasnder completely agree

**Comment by hellosagar** [comment]
@Erifxof what do you mean?
