### ISSUE TITLE
TC Community

### ISSUE THREAD

**Issue by kasnder** [OxfordHCC/tracker-control-android#26]
Other apps, often have Telegram channels or groups to resolve issues more swiftly and discuss new features.

Likewise, Google Groups is widely used.

TrackerControl would greatly benefit from establishing something similar.

**Comment by Atrate** [comment]
If I may, I would suggest a Matrix community (using Riot).

FOSS  decentralized, with the possibility to use E2EE and federation with other services (IRC, Telegram, Discord)

**Comment by kasnder** [comment]
Happy to set this up! Never done this though. Do you have a link at hand to get me started? Or examples of other apps with such communities?

**Comment by Atrate** [comment]
> Do you have a link at hand to get me started?

I've found this to be a good guide: [https://www.snoyman.com/blog/2018/05/guide-to-matrix-riot](https://www.snoyman.com/blog/2018/05/guide-to-matrix-riot)

There's also a big repo of guides here: [https://matrix.org/docs/guides/](https://matrix.org/docs/guides/)

If you need any help, I'm available, I run quite a few rooms and communities on Matrix.

> Or examples of other apps with such communities?

There are many, but the ones I know are: OpenStreetMap, Arch Linux, Riot, Pine64 (and PinePhone), LineageOS, Mjolnij, Synapse (Matrix Synapse), Manjraro, openSUSE, YaST and probably many more.

**Comment by kasnder** [comment]
Thanks, this was very helpful.

I've now set up two communities:
1. Telegram: https://t.me/TrackerControl
2. Matrix: https://matrix.to/#/!htazLJNOSogSGbSPQL:matrix.org?via=matrix.org

Would greatly appreciate your help!
