### ISSUE TITLE
Search new tracker switch button on main page

### ISSUE THREAD

**Issue by lucamp** [OxfordHCC/tracker-control-android#260]
Hi,
when the option "search new tracker" is activated, TC consumes 5 more times the battery, nearly 300 mAh per day on my phone  vs 60 mAh when the option is off.

Unfortunately leaving this off results in some broken site with browser apps (like Firefox), in this case TC per have to learn the trackers and the user have to search and fix before switching off the option again.

Since "search new tracker" is inside the settings it's quite tedious going there every time.

It will be very appreciated having a switch on the main page in the top right corner, or at least under the three dots menu.

Thanks for the app
Luca

Tracker Control 2021.07.23-fdroid

**Comment by kasnder** [comment]
This is an advanced option, and isn't really supported by me. It's just there for people to improve battery use, if they have problems. Often, however, battery use is wrongly attributed to TC.
