### ISSUE TITLE
autorun the app without my knowledge

### ISSUE THREAD

**Issue by OmlineEditor** [OxfordHCC/tracker-control-android#270]
**Describe the bug**
the program runs itself and is stored in memory as a service

**To Reproduce**
1) the program is not running and it is not in memory
2) I am connected to the internet (3G or wi-fi)
3) I see that the program has started itself and is in memory

the error is random or wandering. the program does not always start when connected to the Internet

**Comment by kasnder** [comment]
This is likely intended behaviour: the app regularly checks if it should be running, using a dedicated services. This consumes almost no battery. It is in RAM not because it is cached. If other apps want to use that RAM; that gets wiped.

**Comment by kasnder** [comment]
Apps like Spotify do the same. The reason is the way Android is designed, and TC, Spotify and other apps have to work around that.

**Comment by OmlineEditor** [comment]
I don't need a program in memory. I want the program to close itself if it was not asked to run.
please open the ticket and solve the problem.

**Comment by kasnder** [comment]
> I don't need a program in memory. I want the program to close itself if it was not asked to run.
> please open the ticket and solve the problem.

This is intended behaviour. The app is in RAM temporarily, but doesn’t use battery, and will get removed from RAM if other apps need it. I don’t see a problem.

**Comment by OmlineEditor** [comment]
> I don’t see a problem.

I see this as a problem. I have other applications and they are not in memory. this behavior is wrong. I use your program very rarely, but it always sits in memory. this is not true. Talk about it with other people

**Comment by kasnder** [comment]
> > I don’t see a problem.
> 
> I see this as a problem. I have other applications and they are not in memory. this behavior is wrong. I use your program very rarely, but it always sits in memory. this is not true. Talk about it with other people

As I said, there‘s nothing I can do about this. It’s due to the design of Android, and apps like Spotify or Google Maps do the same. I’m sorry but I can’t fix this. I’ll close this conversation now.
