### ISSUE TITLE
solving the problem from the previous ticket

### ISSUE THREAD

**Issue by OmlineEditor** [OxfordHCC/tracker-control-android#271]
you misunderstood me in https://github.com/OxfordHCC/tracker-control-android/issues/270. the decision on whether the application service will be launched or not is made not by android, but by the application itself. Your application keeps the **_ServiceSinkhole_** running. if i am not using the application then the service should not be running.

please do not limit the dialogue if we have not agreed.

**Comment by kasnder** [comment]
As I already said, it's necessary for the core functionality of TC to check regularly whether it's still running.

**Comment by kasnder** [comment]
I've unlocked both conversations now, and shouldn't have done so in the first place. I'm sorry for that.

Regardless, this is intended behaviour of TC. Please uninstall the app if you don't like it.

**Comment by OmlineEditor** [comment]
I like your app and I want to use it. I don't understand the behavior of the application. Why keep the service always on if the application is not running now and the user is not collecting data? nothing is required from the application now, so nothing should be running. when the user turns on the application and starts data collection, then you need to start the service. now we are not talking about the application itself but about the service **_ServiceSinkhole_**.

please explain to me the logic of the work. I explained my logic.
