### ISSUE TITLE
False positive Virustotal detection for Disconnect blocklist

### ISSUE THREAD

**Issue by primarto** [OxfordHCC/tracker-control-android#30]
Virustotal detect Trojan:

https://www.virustotal.com/gui/file/6e25ab3c677fe0d085387b15438ada367311a32bb28c135fedfcee5680f56400/detection

**Comment by kasnder** [comment]
Thanks for reporting. This is really strange, and will most likely be a false positive.

**Comment by kasnder** [comment]
I investigated this. The VirusTotal detects something for TrackerControl alpha 13 not for 12.

Alpha 13 was the first version to include the disconnect blocklist, a text file:

https://github.com/OxfordHCC/tracker-control-android/blob/master/app/src/main/assets/disconnect-blacklist.json

And indeed, feeding the textfile itself into VirusTotal gives the same detection:

https://www.virustotal.com/gui/file/7918e9f469afb439643bb788ac3a47ddd5c6f3138dee7240dc464c9322ef90a0/detection

**Comment by kasnder** [comment]
This file was just copied from the Mozilla repo. Also for this file, VirusTotal shows the same message: https://github.com/mozilla-services/shavar-prod-lists/blob/master/disconnect-blacklist.json

**Comment by kasnder** [comment]
I guess there are some suspicious domains in the file.

**Comment by kasnder** [comment]
I’ll close this for now because it seems there’s not much I can do to fix this.

**Comment by kasnder** [comment]
This is now fixed.
