### ISSUE TITLE
insecure gradle setup

### ISSUE THREAD

**Issue by uniqx** [OxfordHCC/tracker-control-android#33]
The version of gradlew in this project is ancient (1.6-20130404052254+0000). It does not even support setting `distributionSha256Sum` in `gradle/wrapper/gradle-wrapper.properties`. Which btw. is also something you should do for securing your build tools.

**Comment by uniqx** [comment]
@M66B This is also a problem with NetGuard.

**Comment by kasnder** [comment]
Thanks for flagging this!

I tried to fix this with fe7642b16173e434c73cf473759eb0eee3dcd5de
