### ISSUE TITLE
Enhancement : Run automatically at startup

### ISSUE THREAD

**Issue by marco3mt** [OxfordHCC/tracker-control-android#36]
Would it be possible to add the option "Run automatically at startup" ?

That would be a great improvement. I have been unable to do so  (Huawei 20i) with "TrackerControl" but "Blockada" allows it.

Thanks for your great work !

**Comment by kasnder** [comment]
Thanks for flagging this.

In theory, TrackerControl should start automatically, if it's enabled when you shut down your device.

Although, on some devices, the auto-start of apps is blocked, and you may have to enable this manually from your device settings.
