### ISSUE TITLE
"Failed to install due to an unknown error"

### ISSUE THREAD

**Issue by rjesop** [OxfordHCC/tracker-control-android#39]
Just tried installing from FDroid on Moto G Play Android 7.1.1. Got the above message. I have NetGuard installed if that makes any difference but still wouldn't install even when I killed the NG processes.

**Comment by kasnder** [comment]
Thanks for reporting. This has been fixed in the latest version of TrackerControl.

https://github.com/OxfordHCC/tracker-control-android/releases/tag/2020050802

**Comment by kasnder** [comment]
You can use this version, since it'll take some time until the new version will go live on F-Droid.
