### ISSUE TITLE
Tracker control could not start automatically

### ISSUE THREAD

**Issue by Frank667** [OxfordHCC/tracker-control-android#42]
When trying to start tracker control I ge the notification that it could not start and the message:

> An unexpected error has occured: 'java.lang.SecurityException: getPackageUid: Neither user xxxxx nor current proceess has android.permission.INTERACT_ACROSS_USERS.'

Does this need to be run as root?

**Comment by kasnder** [comment]
There’s no root functionality in the app. Really don’t know what the error means. Will check this!

**Comment by kasnder** [comment]
Has this issue ever occurred again?

**Comment by kasnder** [comment]
I've not been able to gather more detail about this issue, unfortunately..

**Comment by kasnder** [comment]
Closing this for now.
