### ISSUE TITLE
How do i get the tracker control to work?

### ISSUE THREAD

**Issue by Sassymickey05** [OxfordHCC/tracker-control-android#46]

**Comment by kasnder** [comment]
Can you provide some more detail? Make sure you use the latest version of the app, and then enable the app from the top bar!

**Comment by Sassymickey05** [comment]
Can we download the app from github?I cant find it in Google play storePowered by Cricket Wireless
-------- Original message --------From: Konrad Kollnig <notifications@github.com> Date: 5/17/20  9:13 AM  (GMT-05:00) To: OxfordHCC/tracker-control-android <tracker-control-android@noreply.github.com> Cc: Sassymickey05 <sassymickey05@gmail.com>, Author <author@noreply.github.com> Subject: Re: [OxfordHCC/tracker-control-android] How do i get the tracker control to work? (#46) 
Can you provide some more detail? Make sure you use the latest version of the app, and then enable the app from the top bar!

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OxfordHCC/tracker-control-android/issues/46#issuecomment-629796077",
"url": "https://github.com/OxfordHCC/tracker-control-android/issues/46#issuecomment-629796077",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by kasnder** [comment]
Yes. Just go here:

https://github.com/OxfordHCC/tracker-control-android/releases/download/2020050802/TrackerControl-2020.05.08-github-release.apk

**Comment by Sassymickey05** [comment]
This is what that takes me too. I have no idea what I am looking forPowered by Cricket Wireless
-------- Original message --------From: Konrad Kollnig <notifications@github.com> Date: 5/17/20  9:38 AM  (GMT-05:00) To: OxfordHCC/tracker-control-android <tracker-control-android@noreply.github.com> Cc: Sassymickey05 <sassymickey05@gmail.com>, Author <author@noreply.github.com> Subject: Re: [OxfordHCC/tracker-control-android] How do i get the tracker control to work? (#46) 
Closed #46.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OxfordHCC/tracker-control-android/issues/46#event-3344556984",
"url": "https://github.com/OxfordHCC/tracker-control-android/issues/46#event-3344556984",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Sassymickey05** [comment]
![Screenshot_20200517-095156_Chrome](https://user-images.githubusercontent.com/65477368/82149405-c6379f00-9824-11ea-99e3-83a6ec7844f4.jpg)

**Comment by Sassymickey05** [comment]
![Screenshot_20200517-095133_Chrome](https://user-images.githubusercontent.com/65477368/82149461-dbacc900-9824-11ea-9f29-999a8c8a5fe1.jpg)

**Comment by kasnder** [comment]
Sorry for that. Check again here: https://github.com/OxfordHCC/tracker-control-android/releases/tag/2020050802
