### ISSUE TITLE
Latest version overrides my choices with no backup or prompt?

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#48]
You just decided to disable browsers,email and others (including disabling blocking of all apps entirely???) whether I'd gone to the trouble of configuring them or not with no prompt to the user unless they happened to read the changelog and no prompt to backup the existing choices FIRST?  Now I get to redo all of last week's tweaking because the last backup was on the 15th.  Not well done.  It looks like even restoring a backup left many unblocked.  Now my list of trackers has reset to 0 on every app.  If you are not backing up my choices of what to enable/disable and the list of trackers found what the heck ARE you backing up?  The handful of app settings?

A browse of the NETGUARD_<date>.xml file shows it only tracks the apps you totally disabled blocking of...none of the ones where you partially allowed content.  Why is the backup file called Netguard instead of TrackerControl?  I've been recommending this app to my friends but I'll make sure to tell them not to upgrade unless they want to start OVER.

..and every time I restore from a backup you 1) turn blocking of all apps off(slider at top of app)  and turn off browsers, email, bluetooth and half a dozen others I had just finished resetting to ENABLED AGAIN which are NOT listed in the backup.

What a charlie foxtrot.

**Comment by kasnder** [comment]
Very sorry to hear this. There’s no backup functionality yet.

**Comment by kasnder** [comment]
#50

**Comment by kasnder** [comment]
Will add backup functionality, and communicate clearer in the future.

**Comment by famewolf** [comment]
I agree it's an important issue.  It wouldn't be a big deal to a rooted user since they could restore from titanium backup or something similar but as something designed to be "non root" the only way we have to get back to where we were is through the app.  I apologize for "yelling" in first post but it was VERY frustrating.

**Comment by kasnder** [comment]
I fully agree. This shouldn’t happen, and it is really disappointing. I’m really very sorry.

I also thank you for reminding me that it’s a non-root app. This is a central property of TC, and I’ve now added this to the GitHub landing page.

**Comment by kasnder** [comment]
New version should now have working backup:

https://github.com/OxfordHCC/tracker-control-android/releases/tag/2020052101

Let me know if it works for you, and do share the app with others!

**Comment by famewolf** [comment]
Does the f-droid released version and your github released version use the same signed cert?  Otherwise will conflict and I'm uncertain how to override.

**Comment by kasnder** [comment]
Different cert, but also different package names. F-Droid takes a while to update.

**Comment by famewolf** [comment]
Ok I did a full uninstall and reinstall.....I see the high level app status being backed up but if an app has multiple trackers and I've chosen to block Advertising, Analytics and Unrecognized but ALLOW Content is it going to remember those choices?  The quick glance at the code I did didn't look like it.

**Comment by kasnder** [comment]
Oh wow. I didn’t realise that so many tools are unblocked. This wasn’t intended. I may remove email again then.

**Comment by kasnder** [comment]
And, that’s the new feature. Not only the high-level status is included in backups, but also the tracker categories.

**Comment by famewolf** [comment]
Most of those odd apps are being identified as browsers..for example hermit has the option to act as a browser..it would create a "facebook" app that took users to the facebook web page for example.  

I had to reboot the phone to get the trackers to start being recognized which was quirky.

**Comment by famewolf** [comment]
I tested with iheartradio which is showing 3 trackers...I enabled "social" and then did a backup and did see this...A user isn't gonna know what app it is but guess that's no big deal as long as trackercontrol does.

<blocklist>
    <setting key="APPS_BLOCKLIST_APPS_KEY_10195" type="set" value="Social" />
    <setting key="APPS_BLOCKLIST_APPS_KEY" type="set" value="10195" />
  </blocklist>

**Comment by kasnder** [comment]
It’s UIDs. Yet, they get lost if apps are uninstalled, so this is really only to protect TrackerControl..

Guess there’s more work to be done.
