### ISSUE TITLE
Feature Request: Support ad blocking via supplemental host list.

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#49]
Since android  only allows 1 vpn at a time the two mutually exclusive apps to trackercontrol are custom dns/dnsmasq'ing apps.  You at least support specifying dns servers for the vpn even though this does NOT provide dnsmasq or dns over https.  Additionally this is not providing ad blocking as dns66 did.   On first glance it would appear if a secondary host list was allowed either my you or allowing the USER to add one then ad blocking could also be implemented.

**Comment by kasnder** [comment]
Does this address your issue:

https://github.com/OxfordHCC/tracker-control-android/blob/master/ADBLOCKING.md

Custom lists can be used but are very aggressive, and any blocked domains are not shown in the UI.

**Comment by kasnder** [comment]
And then, I really wonder why custom DNS is not supported yet. This is very easy to implement.

**Comment by famewolf** [comment]
Well you do allow specifying primary and secondary dns for the vpn in the app but again that's "regular dns" and not encrypted dns such as dnsmasq or dns over https.

Here's my issue...I have block block domains enabled AND had downloaded the netguard.me/hosts file listed by default.  I'm assuming this means I need to specify a 2nd one for adblocking and APPEND it to the existing?  What's gonna happen when the next auto download of the original happens?  This isn't documented anywhere in the app that I saw either.   It would seem easier to me to have support for say up to 5 lists which can be local or remote...the primary being your netguard list and the additional ones being auto appended.  This would allow for use of online adblocking lists as well as PERSONAL blocklists.   As is several apps still show ads with the netguard.me file in effect.  Perhaps they are using https but I tend to doubt it.

**Comment by kasnder** [comment]
Aah, I see! Encrypted DNS will be a difficult one, because this would be a massive change. But still, a great suggestion.

**Comment by kasnder** [comment]
Ad-blocking has now been added. Multiple lists won't be supported soon.
