### ISSUE TITLE
To access reddit website you have to unblock "social trackers" even if "content" allowed in apps.

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#54]
This appears true for multiple browsers checked.  The ideal situation would be more fine grained control of the trackers so the user could indicate individually how they want this handled..ie social trackers showed facebook and reddit.  I'd NEVER want to allow facebook social tracking but would enable reddit to access the site although I would have thought having "content" enabled should have taken care of it.

**Comment by kasnder** [comment]
Good point! Am considering this. :)

**Comment by kasnder** [comment]
This is a rather ambitious change though, because it potentially changes quite a lot in the app. So, beat with me if this doesn't happen until tomorrow.
