### ISSUE TITLE
(Un)Blocking of individual domains

### ISSUE THREAD

**Issue by kasnder** [OxfordHCC/tracker-control-android#55]
Addresses #54

**Comment by xf-** [comment]
Would be really nice. Some apps use 5-10 google services under content and firebase is a required as data source.

**Comment by kasnder** [comment]
Any ideas how to implement this nicely in the user interface?

**Comment by xf-** [comment]
Maybe some kind of allowed list and maybe add the matched domains into a select. Such things are always ugly, but also the last option and not needed that often. Select could be with an header under blocked stuff. Maybe highlight in boxes if something matches.

**Comment by kasnder** [comment]
I've now implemented an option to exclude individual companies.

**Comment by kasnder** [comment]
Maybe, Firebase shouldn't be included in the first place. Do you have a particular domain name that causes you trouble?

**Comment by kasnder** [comment]
Added in upcoming version. One will be able to block by company.
