### ISSUE TITLE
Netguard seems similar

### ISSUE THREAD

**Issue by mannp** [OxfordHCC/tracker-control-android#58]
I tried your app and it seemed to be the same layout as Netguard, but I couldn't find any shouts out to the Netguard Devs?

Wondered if it was just a coincidence?

**Comment by kasnder** [comment]
It’s absolutely based on NetGuard, which is mentioned here:

https://github.com/OxfordHCC/tracker-control-android

The functionality is different though, and not really related to NetGuard.

How would you change the credits?

**Comment by mannp** [comment]
Not wishing to belittle any party but just felt at first glance most of the menus and blocking tech, hosts file, lists of apps is very close to Netguard, while your app blocks those trackers that I see on Netguard, but have to block manually. 

I presume the author of Netguard is cool with his credits, so I would have nothing to add.

**Comment by kasnder** [comment]
I get your point, and completely agree. NetGuard is a Great piece of work, and I’m trying to use as little code as possible. I guess overall NetGuard is more powerful, whilst this app is a bit easier to use.

Let me know if you have any suggestions!
