### ISSUE TITLE
Allow daily, weekly, monthly automated backups to application folder on sdcard.

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#60]
Allow for automated backups to be setup on a daily, weekly or monthly basis and store the backup's in a TrackerControl subdir on the storage media to prevent cluttering up the default folder which is Download or the root directory of the sdcard.   

Optional Segments:
1) Add time to the backup filename as a 2nd backup on the same day currently gets saved as TrackerControl_20200522.xml (1)
2) Roll the last daily backup of the week into a weekly backup and reset the daily's.  Roll the last backup of the month into a monthly backup and reset the daily and weeklies.  
3) Add list of apps mapped to their uid's in backup so when restoring the correct app is setup even if the uid has changed.  Map them based on their com.google.xxx.xxx names. (see #4)
4) Organize the backup so the subcategories are stored right after the high level app boolean true/false.  This organization may make it easier for you to handle #3.

Wishlist: Fine grained control down to the individual tracker.  I understand some of this is "pie in the sky" stuff.

**Comment by kasnder** [comment]
What would be the advantage of regular backups over manual backups?

**Comment by famewolf** [comment]
same as for a pc automation always beats a manual process.  As it stands I'm making a backup every single time I have to tweak an app to make it work correctly which ends up being more often than what I'm proposing.   F-Droid or github can update the app at ANY time potentially causing data loss and this would ensure the closest backup would only be a day old.    In the event there ends up being a problem keeping a weekly and monthly allows you to jump backwards till a compatible app is found or perhaps you've re-installed apps you'd previously uninstalled and now want to use a backup that had those apps defined.  (of course that brings up idea user specified program "restore from backup" could be useful too.)

**Comment by kasnder** [comment]
I think a nice solution would be Tasker integration for backups.

But then, why not use other Android backup solutions?

**Comment by famewolf** [comment]
Because again, we are not rooted and the only app with permission to access the data is YOUR app.

**Comment by kasnder** [comment]
Good point.

I should enable Android backups for the app!

**Comment by kasnder** [comment]
This works by setting `android:allowBackup="true"`, and should allow you to use other solutions.

**Comment by famewolf** [comment]
As long as I can automate the backups I'm happy although I question directing the solution to a closed source app (even though I personally do own tasker) vs an open source one.  Thanks for not getting annoyed with all the issues I've submitted.

**Comment by kasnder** [comment]
That’s alright! It’s good that you challenge the app a little, to make it better for everyone. :)

**Comment by kasnder** [comment]
I'm closing this for now because the options of TrackerControl to control tracking remain limited, to make users' lives easy.
