### ISSUE TITLE
User specified whitelist and blacklist for specific trackers.

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#62]
There are apps that fail to work unless you unblock the entire app because it needs access to some of the trackers such as "android.googleapis.com" or similar.   Granular control would allow the user to allow that one while still blocking the other *.googleapis.com.   On the other side when using the alexa app it makes some calls to amazon analytics that may not be in the general blacklist but could be added by the user.   

Optional Segment:  For the user to know what they need to block/unblock the app would need to specify the app name in addition to the domain names resolved.  Currently domains resolved is shown but I'm unsure if it's showing ALL or only the ones it blocked.  In either case adding app name would allow adjusting the blocking.

This is very important in figuring out WHY an app is not working.  For example, google voice, google drive and gmail can all block their own analytics but won't work until google system framework is unblocked.  Figuring out what needs to be unblocked is currently a "pin the tail on the donkey" process.  Google system framework has 15+ trackers in it under 1 category and currently ALL have to be allowed.  Granular control would allow only some of them to be allowed.

**Comment by kasnder** [comment]
Absolutely agree. I’m working on granular control but it’s a long shot!!

**Comment by kasnder** [comment]
See #55
