### ISSUE TITLE
Block Internet altogether

### ISSUE THREAD

**Issue by roman82101** [OxfordHCC/tracker-control-android#63]
Hello, I liked your application. In my opinion, to ensure greater confidentiality, it would not be bad to add blocking access to the Internet. Or rather, that there were three modes: Blocking trackers (as it is now), Blocking the Internet and Without blocking trackers, but so that traffic would go through the application (VPN), since it is desirable to enable “Block connections without VPN” in the phone’s VPN settings. The idea came after I noticed that applications that are not allowed to access the Internet through the firmware settings still connected to the network through your application, and when the trackers were disabled, they could no longer go online. Thank you for the attention

**Comment by kasnder** [comment]
Really sorry to hear that you had problems with the apps. I agree that block internet functionality would be good!

**Comment by kasnder** [comment]
I added this in the upcoming version of TrackerControl!

**Comment by roman82101** [comment]
I express my deep gratitude for the work done

**Comment by kasnder** [comment]
Beta is in the Telegram group: https://t.me/TrackerControl

If you have a spare minute, please give it a try!

Should go online soon, if no issues arise.
