### ISSUE TITLE
Toggling groups in trackers menu doesn't persist unless toggle itself tapped

### ISSUE THREAD

**Issue by DrTexx** [OxfordHCC/tracker-control-android#64]
Hi there, absolutely love this app with all my heart, thank you so much for creating it and continuing it's development :heart:.

I've experienced an issue when disabling specific groups of trackers for an app (e.g. 'analytics', 'social', etc.) where state changes will not persist unless I tap the actually toggle UI element itself on a group.

When I tap the group itself, the toggle state visually changes, however isn't persistent between leaving the page and going back to it; actual blocking/whitelisting behavior also doesn't appear to change state if the toggle itself is not tapped.

Please let me know if you need any further details and I'm happy to oblige :slightly_smiling_face:

**Comment by kasnder** [comment]
Very good spot. Thanks for reporting this, I’ll do my best to fix this ASAP!

**Comment by kasnder** [comment]
And many thanks for your support!

**Comment by DrTexx** [comment]
Any time!

**Comment by kasnder** [comment]
This is fixed now, and will be rolled out in the next update!
