### ISSUE TITLE
Return 1x1 pixel gif for blocked domains vs just blocking? Avoid timeouts

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#65]
I'm noticing in web browsers sometimes pages take extended times to load a page...upon looking at what urls they are loading I noticed several were being blocked.  Is trackercontrol just letting the calls time out?  If so you may want to look at why adaway added a built in web server to return a 1x1 pixel gif to avoid the extended timeouts that were resulting.

**Comment by kasnder** [comment]
This is indeed true. I like the idea of serving some content, although the danger with this is that it breaks things.

By contrast, if you let network requests fail, apps might try again to send data.

Timeout is probably the safest implementation.

**Comment by famewolf** [comment]
In browsers you are talking about it taking 20+ seconds for a page to load because it's waiting on multiple timeouts.  Why not let the user pick per app?

**Comment by kasnder** [comment]
Ideally, I’d like to decrease per-app settings, and make TrackerControl as easy as possible.

You mention a very good point. There might be special treatment for browsers added to TrackerControl, so we can avoid annoying timeouts.

**Comment by xf-** [comment]
I disabled it for Firefox nightly/preview (maybe it is now in stable).
Firefox started to support some addons including Ublock Origin and NoScirpt. (and some other Addons like privacy badager, https everywhere, decentraleyes and more)

**Comment by kasnder** [comment]
Firefox also comes with a similar list of trackers. So, this is a good approach.

**Comment by famewolf** [comment]
Firefox developer preview also has over 30 trackers.   I use bromite  (privacy oritented version of chromium)  Can you not just add a toggle so the user can select the browsers manually and those can feed the pixel?  Reading google news and having to go do something for 1/2 a minute evry time I want to read an article is getting OLD.

**Comment by kasnder** [comment]
The idea behind timeouts is to avoid having apps call a host repeatedly. This seems like good behaviour by default. I see that browsers would profit from a change to timeouts but also see that there are browsers that include better tracking protection by default. I won't address this issue soon, though I'll keep it at the back of my mind because it's a very important consideration.
