### ISSUE TITLE
Upgrading to new version disables tracker control

### ISSUE THREAD

**Issue by famewolf** [OxfordHCC/tracker-control-android#68]
When a user installs the new version the slider in the app is disabled even if it was previously enabled.   If the user doesn't open the app they won't know and could run without for quite a while.  There's no real reason it SHOULD be disabling itself either I don't believe?

**Comment by kasnder** [comment]
Thanks for reporting this. I guess the app is stopped after the update, and has to be manually enabled again.

**Comment by kasnder** [comment]
It seems that it’s possible to restart the app automatically though.

https://stackoverflow.com/questions/2133986/how-to-know-my-android-application-has-been-upgraded-in-order-to-reset-an-alarm

**Comment by kasnder** [comment]
The automatic enabling should already be implemented. Weird that it doesn’t seem to work..

**Comment by kasnder** [comment]
I'm closing this for now. Hope the issue hasn't occurred again!

**Comment by kasnder** [comment]
If it has, let me know what version of TrackerControl you're using! F-Droid?
