### ISSUE TITLE
Take Dark mode out of Beta

### ISSUE THREAD

**Issue by xf-** [OxfordHCC/tracker-control-android#75]
Popup/modal "OK" button color and background color are both dark and not readable with low backlight.

THX for the dark theme beta :)

**Comment by kasnder** [comment]
Thanks for reporting this. Haven't really found a nice colour scheme yet..

**Comment by xf-** [comment]
Maybe add a dark Screenshot. First thing i often look for in an interesting app is a dark skin (or even Black for the OLED display). Since Android 10 with dark theme support nothing lights up anymore.

The green is to dark. I notice now the headers above the settings. Maybe stick with wine red for headers and options.

Current
![Screenshot_20200707-154439](https://user-images.githubusercontent.com/1295633/86791278-a759ca00-c069-11ea-806e-9ac9f76cafb9.jpg)

Coloured
![Screenshot_20200707-154439](https://user-images.githubusercontent.com/1295633/86792224-8e9de400-c06a-11ea-9184-6366ee8cfdd7.jpg)

Colourtool helps me sometimes
https://encycolorpedia.de/b8181e

**Comment by kasnder** [comment]
This looks really really good!

If it's convenient for you, could you put your improved colour settings into a pull request?

**Comment by kasnder** [comment]
This should be fixed now. Let me know if the new dark mode works for you!

**Comment by xf-** [comment]
works for me since last update a few days ago
