### ISSUE TITLE
Problem with FTP using the phone as Hotspot

### ISSUE THREAD

**Issue by rebelcode-xr** [OxfordHCC/tracker-control-android#78]
This app is great but sadly gives me problems when I connect my laptop to the hotspot of my phone: I cannot upload files through FTP (using Cyberduck or other apps on the laptop). Often (not always) creates a 0kb file with no content: that's pretty bad if you edit a PHP file, because it deletes everything. 🤯

**Comment by kasnder** [comment]
What a weird error indeed. Thanks for reporting this!

**Comment by rebelcode-xr** [comment]
Hope you can find a solution! 🙏

**Comment by kasnder** [comment]
Maybe, can you try to enable subnet routing from the TrackerControl settings?

**Comment by kasnder** [comment]
Closing this for now, as it'll be difficult to address.
