### ISSUE TITLE
Internet Blocking (Wi-Fi/Cellular Data)

### ISSUE THREAD

**Issue by puppykickr** [OxfordHCC/tracker-control-android#80]
Thank you for this great app!
I have had it for a while, and just finally got it set up and implemented.

So far, so good.

Before this, I was using a very simple firewall, NoRoot Firewall.
Tracker Controller stepped right in and took its place.

But, I did notice one thing that could be an improvement.

On a firewall, you can choose which type of access to allow or deny-  Wi-Fi, cellular data, or both.

![07-14-2020_21-02-23](https://user-images.githubusercontent.com/44860287/87494783-85d28280-c615-11ea-93e7-cf650a30e8d4.jpg)

Tracker Controller only allows total internet blocking or total access.
I do have some apps that I like to limit to one or the other.

**Comment by kasnder** [comment]
Nice to hear the app is useful for you!

How would this feature help you?

**Comment by puppykickr** [comment]
Because some apps only need Wi-Fi access, and some apps only need cellular data access.

Also, it xould be beneficial to others, if they don't want certain apps to use data when on mobile networks, but desire the app to have access when on Wi-Fi.

Games, and even some system apps come to mind.

This would prevent the user from needing to go into the settings and change app access repeatedly.

**Comment by puppykickr** [comment]
Also, as you know, Android only allows one app to use the VPN service at a time.

Many firewall apps, such as NoRoot Firewall and NetGuard, use the VPN service in order to function.

Tracker Control also uses this same VPN service, so that type of firewall cannot be used at the same time as Tracker Control.

So, although Tracker Control is centered around the elements of online tracking, I hope that you can see that it would increase your field of prospective users by adding the split access feature.

As it is now, there is already the capability to block access conpletely.

The app would become that much more useful, and even be able to be a better firewall than the other two that I mentioned, actually a firewall with tracker control, which I have never seen.

Tracker Controlling Firewall, if you will.

**Comment by kasnder** [comment]
Ah. Does your Android version not allow to block cellular from the system settings?

**Comment by puppykickr** [comment]
Well, of course.
But it is global.
So a phone call would not be able to come through, and no texting either.

I can't just set individual apps to be able to use/not use Wi-Fi/cellular on a per app basis by using the device.

If that was possible, then there would be no need for a firewall.

**Comment by jawz101** [comment]
@puppykickr there is a toggle in each app settings screen to disable background data.

NetGuard provides a shortcut to launch each app's settings screen (icon looks like a cog wheel).  It would be nice if TC had kept that button next to each app in the main app screen

**Comment by kasnder** [comment]
> @puppykickr there is a toggle in each app settings screen to disable background data.
> 
> NetGuard provides a shortcut to launch each app's settings screen (icon looks like a cog wheel). It would be nice if TC had kept that button next to each app in the main app screen

Such button exists. Click the app -> menu -> uninstall

Whilst it says 'uninstall', it just opens the app settings.

**Comment by kasnder** [comment]
Since newer Android version offer this feature, I won't prioritise this for now.

However, I'm trying to work on something that other firewall apps don't have: blocking tracker communications of non-foreground apps. I think this could reduce tracking much more than discrimination between WiFi/Cellular. #89
