### ISSUE TITLE
Domain Whitelist for Ad-Blocker

### ISSUE THREAD

**Issue by puppykickr** [OxfordHCC/tracker-control-android#81]
I use a browser with a hostfile ad-blocker, similar to the one in Tracker Controller.

In fact, I think it may download the same hostfile by default.

Anyway, I found that many common sites were blocked.
Lucky for me, the browser has a whitelist function to allow a site to quickly be allowed to connect.

I would like to be able to implement the hostfile of Tracker Controller, for the other apps on my devices besides the browser.

But without a whitelist, then these same sites will become blocked once again in the browser.

**Comment by kasnder** [comment]
This is coming. 🙂

**Comment by kasnder** [comment]
Related to #55

**Comment by kasnder** [comment]
Added in upcoming version.
