### ISSUE TITLE
Limited use of ACRA for opt-in crash reporting

### ISSUE THREAD

**Issue by desk7** [OxfordHCC/tracker-control-android#83]
As also mentioned [here](https://community.e.foundation/t/trackercontrol-a-way-to-neutralize-in-app-trackers/9407/56), I saw that Tracker Control contains a tracker itself!
I know that it's an open source Application Crash Reports but I was very surprised, however, as neither the github page nor the app mentions this tracker and there is no option to disable it.
Given the crucial importance of this app and since a similar app like Netguard doesn't have trackers, I'd like to ask you to delete trackers at all.

**Comment by kasnder** [comment]
Good point. I’ll clarify this. The important difference though is that it’s not really a tracker. It does not send data off your device.

Instead, it opens a window when the app crashes, from which you can send an email to me.

No data is ever collected in the background or with the user not knowing. I don’t even have any servers to which I could send data.

**Comment by kasnder** [comment]
I added to the privacy policy that TrackerControl never sends any personal data off your device: https://github.com/OxfordHCC/tracker-control-android/blob/master/README.md#privacy-notice

I also added that ACRA is set up in a way that it does NOT collect any user data.

**Comment by kasnder** [comment]
Sorry for the confusion!!

**Comment by desk7** [comment]
Thank you for clarifying!

**Comment by kasnder** [comment]
Really trying to use the best privacy practices here, and I could’ve done a bit better on this one..

Thanks for raising it!

**Comment by kasnder** [comment]
The relevant line in the code in this one:

https://github.com/OxfordHCC/tracker-control-android/blob/0c28b8a1f2819f89f319c0ea9e2443a599ec2c03/app/src/main/java/eu/faircode/netguard/ApplicationEx.java#L52

**Comment by kasnder** [comment]
Crash reports are also set up such that they send less data than the default, so that no personal data is contained:

https://github.com/OxfordHCC/tracker-control-android/blob/0c28b8a1f2819f89f319c0ea9e2443a599ec2c03/app/src/main/java/eu/faircode/netguard/ApplicationEx.java#L42

**Comment by kasnder** [comment]
I'll close this here, since I added information on this to the Readme.
