### ISSUE TITLE
Add in-app downloader to TC's Update Notification

### ISSUE THREAD

**Issue by hb02** [OxfordHCC/tracker-control-android#93]
Tried the search but did'nt find anything.

I know you are deploying a full featured App at F-Droid or as a Download at github. YOu also have a "slim"-Version at GooglePlay.

Have you discussed an inApp-Updater for your GitHub-Release? I prefere it to grant your app more permissions than another filemanager/browser etc.

Kind Regards

This is my First Issue ever on GitHub - Sorry for any mistakes

**Comment by kasnder** [comment]
The GitHub version should comes already with an updater. You should be notified whenever new updates are released. Is this not working for you? Is there a way to improve this?

**Comment by hb02** [comment]
Sorry for my bad description. You are right - i get an inAppNotification, but to carify following would be awesome:

If I tip on these notification there should be an option for automatic download and installation within the application.
eg:
![grafik](https://user-images.githubusercontent.com/6522865/89767879-17d98800-dafb-11ea-852e-181e6bce0496.png)

or

![grafik](https://miro.medium.com/max/1000/1*4iiK9MjRzvvpwU1DpXdGrQ.png)


Hope this helps

**Comment by kasnder** [comment]
I absolutely see that this would be a much better implementation, and thanks for suggesting this.

At the moment, I'm working on more granular blocking of tracker domains. Once this is done, I'll be continue to improve TC around the edges.

Best,

Konrad

**Comment by kasnder** [comment]
I've now implemented more granular blocking and reconsidered this issue.

Since there already exists an updater, I'll continue to prioritise other aspects of the app, with the aim of improving the blocking of trackers. I think a better UI for update would be nice, but not essential for the core functionality of the app. I'm closing this for now.
