### ISSUE TITLE
Add bulk editing of Internet access for apps

### ISSUE THREAD

**Issue by rogerxed** [OxfordHCC/tracker-control-android#94]
Please add black/whitelist mode for the internet access like in the netguard. I want to turn off the internet of the installed and system apps completely, but by default it is all turned on, turning off all these app including system apps one by one takes lots of time, please add it.

**Comment by kasnder** [comment]
I see your point. I think the NetGuard approach is not super intuitive for all users. What seems like a good addition though is some sort of 'bulk edit', e.g. disable all apps at once.

**Comment by rogerxed** [comment]
That would be really helpful

**Comment by kasnder** [comment]
I realised this is similar to #53

If you select 'sort on name', you'll see the apps excluded from blocking to the top.

I'll try to emulate something similar for internet access because this would be a very valuable addition to the app.

**Comment by kasnder** [comment]
I've now added this to the upcoming TrackerControl version.
